### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#1008]
Got this error while running the SLF script with 12 participants

INFO:AFQ:Saving /Users/jyeatman/AFQ_data/HBN/derivatives/afq_slf/sub-NDARKV461KGZ/ses-HBNsiteRU/bundles/sub-NDARKV461KGZ_ses-HBNsiteRU_acq-64dir_space-T1w_desc-preproc_dwi_space-RASMM_model-probCSD_algo-AFQ_desc-LSLF3_tractography.trk
INFO:AFQ:Preparing Segmentation Parameters
INFO:AFQ:Preprocessing Streamlines
INFO:AFQ:Assigning Streamlines to Bundles
INFO:AFQ:Finding Streamlines for L_SLF1
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0009419918060302734s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 56112/56112 [00:08<00:00, 6247.93it/s]
INFO:AFQ:After filtering by include (time: 10.66758394241333s), 1126 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.09030508995056152s), 892 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.20418500900268555s), 217 streamlines remain.
INFO:AFQ:Finding Streamlines for L_SLF2
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0008969306945800781s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 56112/56112 [00:22<00:00, 2529.43it/s]
INFO:AFQ:After filtering by include (time: 64.6264967918396s), 3922 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.8390789031982422s), 3175 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.3956570625305176s), 1560 streamlines remain.
INFO:AFQ:Finding Streamlines for L_SLF3
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0017559528350830078s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
 39%|██████████████████████████████████████▋                                                            | 21900/56112 [00:18<00:58, 583.76it/s]/Users/jyeatman/miniconda3/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
 71%|█████████████████████████████████████████████████████████████████████▏                            | 39588/56112 [00:36<00:13, 1257.30it/s]zsh: killed     /Users/jyeatman/miniconda3/bin/python 
(base) jyeatman git/pyAFQ [SLF123new] $

**Comment by arokem** [comment]
Yeah. We're seeing quite a few of these on the CI as well. I wonder whether we should rethink our approach to parallelization, at least in the default case.

**Comment by jyeatman** [comment]
How can I change this to get it to run?

**Comment by arokem** [comment]
I think if you add to your call to initialize the GroupAFQ object the following key-word argument it will avoid joblib/loky

```
segmentation_params = {"parallel_segmentation": {"engine":"serial"}}
```

**Comment by arokem** [comment]
@36000 : have you tested this much with other engines? Should we try setting dask as the default engine?

**Comment by arokem** [comment]
Implemented in #1009. @jyeatman : if you'd like to try that (which would be helpful!), you'd set: 

```
segmentation_params = {"parallel_segmentation": {"engine":"dask", "n_jobs": -1}}
```

**Comment by jyeatman** [comment]
Just added that and have this ambiguous error

INFO:AFQ:Saving /Users/jyeatman/AFQ_data/HBN/derivatives/afq_slf/sub-NDARKV461KGZ/ses-HBNsiteRU/bundles/sub-NDARKV461KGZ_ses-HBNsiteRU_acq-64dir_space-T1w_desc-preproc_dwi_space-RASMM_model-probCSD_algo-AFQ_desc-LSLF3_tractography.trk
INFO:AFQ:Preparing Segmentation Parameters
INFO:AFQ:Preprocessing Streamlines
INFO:AFQ:Assigning Streamlines to Bundles
INFO:AFQ:Finding Streamlines for L_SLF1
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0010781288146972656s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 6.4283668994903564s), 1126 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.10619688034057617s), 892 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.44379115104675293s), 217 streamlines remain.
INFO:AFQ:Finding Streamlines for L_SLF2
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0010323524475097656s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
INFO:AFQ:After filtering by include (time: 16.972256898880005s), 3922 streamlines remain.
INFO:AFQ:Filtering by exclude
INFO:AFQ:After filtering by exclude (time: 0.32108426094055176s), 3175 streamlines remain.
INFO:AFQ:Filtering by Mahalanobis
INFO:AFQ:After filtering by Mahalanobis (time: 0.2075059413909912s), 1560 streamlines remain.
INFO:AFQ:Finding Streamlines for L_SLF3
INFO:AFQ:Filtering by Cross Mid.
INFO:AFQ:After filtering by Cross Mid. (time: 0.0012192726135253906s), 56112 streamlines remain.
INFO:AFQ:Filtering by include
zsh: killed     /Users/jyeatman/miniconda3/bin/python

**Comment by arokem** [comment]
Is this with `"serial"` or with `"dask"`?

**Comment by jyeatman** [comment]
segmentation_params = {"parallel_segmentation": {"engine":"dask", "n_jobs": -1}}

**Comment by jyeatman** [comment]
now running 
segmentation_params = {"parallel_segmentation": {"engine":"serial"}}

**Comment by 36000** [comment]
So that warning and the memory leak warnings in general from loky/joblib happen when the program crashes for some other reason and it doesn't have time to clean up, at least in my experience

**Comment by jyeatman** [comment]
Ran with the following parameters on 12 HBN subjects with very high QC scores and the results look good!

```
my_afq = GroupAFQ(
    bids_path=study_dir,
    preproc_pipeline="qsiprep",
    output_dir=op.join(study_dir, "derivatives", "afq_slf"),
    brain_mask_definition=brain_mask_definition,
    tracking_params={"n_seeds": 4,
                     "directions": "prob",
                     "odf_model": "CSD",
                     "seed_mask": RoiImage()},
    clean_params={"clean_rounds": 20,
                  "length_threshold": 3,
                  "distance_threshold" : 3,
                  },
    segmentation_params = {"parallel_segmentation": {"engine":"serial"}},
    bundle_info=bundles)
```
![bundle-L_SLF1_view-sagittal_idx-0_montage](https://github.com/yeatmanlab/pyAFQ/assets/1775818/faaa462f-1b8c-43f1-b2b6-5e21ff2c9435)
![bundle-L_SLF2_view-sagittal_idx-0_montage](https://github.com/yeatmanlab/pyAFQ/assets/1775818/e58c8fe0-bd35-442c-b395-d35093b41bf8)
![bundle-L_SLF3_view-sagittal_idx-0_montage](https://github.com/yeatmanlab/pyAFQ/assets/1775818/14703aee-2a6e-4a4b-8fc2-383101bca66e)

**Comment by arokem** [comment]
🤩
