### ISSUE TITLE
Issue with tractography output files and BIDS format

### ISSUE THREAD

**Issue by pierre-nedelec** [yeatmanlab/pyAFQ#1013]
Two output tractography files are created each time, their path differing only with the addition of `algo-AFQ_` for the one with classified bundles. This way of naming does not seem to be BIDS friendly. First `algo` is not a default recognized BIDS entity. This can be worked around for nor now [like this](https://github.com/bids-standard/pybids/issues/1020#issuecomment-1703233782). However a problem remains: if you try to access the file without the algo descriptor, you can't just using bids' `layout.get()` to access the one file that doesn't have "algo" setup.

```
from bids.layout import BIDSLayout, add_config_paths
from bids.exceptions import ConfigError
from pathlib import Path

root_dir = Path("to/your/BIDS/dataset")

try:
    add_config_paths(
        **{
            "bidsafq": "path/to/bidsafq.json"
        }
    )
except ConfigError as e:
    print(e)
except Exception as e:
    raise e

layout = BIDSLayout(root_dir)
layout.add_derivatives(root_dir / "derivatives", config=["bids", "bidsafq"])
params = {
    "subject": layout.get_subject()[0],
    "session": layout.get_sessions()[0],
    "extension": "trx",
    # "return_type": "filename",
    "suffix": "tractography",
    "algorithm": "AFQ",
}
layout.get(**params)
```
<details>
  <summary>Attaching here again the json config</summary>

```json
{
  "name": "bidsafq",
  "entities": [
    {
      "name": "algorithm",
      "pattern": "[_/\\\\]+algo-([a-zA-Z0-9]+)"
    }
  ]
}
```
</details>

With `"algorithm": "AFQ",` it returns one file. Without it, it returns both files. And I don't think there is way to access just the other one?

**Comment by pierre-nedelec** [comment]
A follow up issue here: if running [pyAFQ](https://github.com/yeatmanlab/pyAFQ) after [QSIprep](https://github.com/PennLINC/qsiprep) (@mattcieslak), some entities are used twice, e.g. `desc`. Here's a path demonstrating this:
```
..._run-1_space-T1w_desc-preproc_dwi_space-RASMM_model-probCSD_algo-AFQ_desc-profiles_dwi.csv
```
(the suffix `_dwi_` is also repeated btw)

This makes the `layout.get(desc='profiles')` unusable, as it only parses the first occurence.

One potential solution for pipelines developers could be for them to create their own `Entities`? Or should we stick to [BIDS classic entities](https://bids-specification.readthedocs.io/en/stable/glossary.html) — in which case I'm not sure how to handle repeat entities?

**Comment by arokem** [comment]
Thanks for raising this. Indeed, when we started formulating these file-names we did not follow the standard very closely. And the concatenation of file-names doesn't make much sense either - agreed about that.

I like the idea of creating custom entities here. This could serve as a basis for advocating for specific entities that would be included in the BIDS spec down the line. It will also probably make it easier to adopt/replace entities that supplant our development, once they are integrated upstream. 

Do you want to give this a shot? For example, defining the algorithm entity?

**Comment by 36000** [comment]
Yes, I think defining a series of new entities makes sense here, though I wonder how this interacts with existing efforts in the BIDS communities to make standards for dMRI derivatives?

**Comment by arokem** [comment]
I think that it would be helpful to these efforts, because it would provide a set of examples of entities and use-cases for these entities. Once things solidify upstream, we can hopefully more easily adopt the standard way of doing things.

**Comment by 36000** [comment]
I will make a PR to remove the additional suffix, and replacing desc- with something else and algo- with segalgo-. @pierre-nedelec , do u have code that we could use as a starting point for an example demonstrating the use entities?
