### ISSUE TITLE
Memory error when plotting tract profiles with my own data

### ISSUE THREAD

**Issue by Youguang** [yeatmanlab/pyAFQ#102]
The plotting tract profiles example works well, but when I run it with my own data, it shows MemoryError when tracking:

> Dataset is already in place. If you want to fetch it again please first remove the folder /home/z/.dipy/stanford_hardi 
> Calculating DTI...
> Tracking...
> 
> ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
> <ipython-input-2-ce5383ca7bfd> in <module>()
>      35 print("Tracking...")
>      36 if not op.exists('dti_streamlines.trk'):
> ---> 37     streamlines = list(aft.track(dti_params['params']))
>      38     aus.write_trk('./dti_streamlines.trk', streamlines, affine=img.affine)
>      39 else:
> 
> ~/anaconda3/lib/python3.5/site-packages/AFQ/tractography.py in track(params_file, directions, max_angle, sphere, seed_mask, n_seeds, random_seeds, stop_mask, stop_threshold, step_size, min_length, max_length)
>     107         evals = model_params[..., :3]
>     108         evecs = model_params[..., 3:12].reshape(params_img.shape[:3] + (3, 3))
> --> 109         odf = tensor_odf(evals, evecs, sphere)
>     110         dg = dg.from_pmf(odf, max_angle=max_angle, sphere=sphere)
>     111 
> 
> ~/anaconda3/lib/python3.5/site-packages/AFQ/dti.py in tensor_odf(evals, evecs, sphere)
>     137 
>     138     lower = 4 * np.pi * np.sqrt(np.prod(evals[mask], -1))
> --> 139     projection = np.dot(sphere.vertices, evecs[mask])
>     140     projection /= np.sqrt(evals[mask])
>     141     odf[mask] = ((vector_norm(projection) ** -3) / lower).T
> 
> MemoryError: 

Thank you.

**Comment by arokem** [comment]
Thanks for reporting this @Youguang! 

Could I ask for a few more details? 

- What is the size of the data (the shape of the dwi data array, including number of directions)? 
- How much memory does your computer have?

**Comment by Youguang** [comment]
Hi @arokem , thanks for your reply.

The data size 2.2GB, consists of 129 volumes. It was acquired with voxel size 1.25x1.25x1.25 mm^3, and resampled to 1x1x1 mm^3 when preprocessing. And it is mult-shelled, the b values vary from 180 to 3000 s/mm^2. The same data can be processed with matlab afq toolbox, and the whole-brain tracking results looks well, but it fails to extract data from some WM tracts, so I turned to python-afq to have a try.

And I run it on ubuntu server 16.04 with anaconda3 environment in jupyter notebook, it's memory is 64GB. When it start tracking, the memory occupation was linearly increasing until it reported memory error.

**Comment by arokem** [comment]
That's a pretty large amount of data. The largest dataset that I have analyzed with pyAFQ are acquisitions from the HCP, which are about 1 GB in size. 

There would be a bit more data munging to do, and a bit more programming, but you can use the API directly to feed in the tracks from the Matlab version into the segmentation part of the pyAFQ software, possibly circumventing this memory error. It might take a long while to do the segmentation, though.

**Comment by arokem** [comment]
Given how old this issue is, I am going to go ahead and assume that this is no longer an issue. I am going to close this, but feel free to reopen if you are still dealing with this.
