### ISSUE TITLE
GroupAFQ and BIDS error

### ISSUE THREAD

**Issue by radhi-bhalerao** [yeatmanlab/pyAFQ#1039]
I keep getting this error while initializing a GroupAFQ object “No dwi found for subject PDa### and session 1. Skipping.”

myafq = GroupAFQ(
    bids_path=('/data/morrison/data/parkinsons/retro_clin_dti_bids/Nifti'),
    viz_backend_spec='plotly_no_gif',
	bids_filters= {'suffix': 'dwi', 'session': '1', 'datatype': 'dwi'})

<img width="268" alt="Screen Shot 2023-10-04 at 12 28 27 PM" src="https://github.com/yeatmanlab/pyAFQ/assets/83267360/3cc1fba4-5820-4db4-bd56-c20bb4e567a8">

Any suggestions of maybe what I'm doing wrong in the bids organization?

**Comment by arokem** [comment]
Does this dataset validate as BIDS-compliant? You can easily check here: https://bids-standard.github.io/bids-validator/

I suspect that the file PDa001_dti.nii.gz might cause some issues unless it is recorded in the .bidsignore file of the dataset.

**Comment by 36000** [comment]
Another option here is to use ignore BIDS and use ParticipantAFQ:
```
myafq = ParticipantAFQ(
  '/data/morrison/data/parkinsons/retro_clin_dti_bids/Nifti/derivatives/sub-PDa001/ses-1/sub-PDa001_ses-1_dwi.nii',
  '/data/morrison/data/parkinsons/retro_clin_dti_bids/Nifti/derivatives/sub-PDa001/ses-1/sub-PDa001_ses-1_dwi.bval',
  '/data/morrison/data/parkinsons/retro_clin_dti_bids/Nifti/derivatives/sub-PDa001/ses-1/sub-PDa001_ses-1_dwi.bvec',
  some_path_to_output_folder)
```
