### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by haijunkenan** [yeatmanlab/pyAFQ#1065]
I have tried python environment with python3.8 and python3.9, and then install pyAFQ, but it still failed with
"ImportError: cannot import name 'track' from 'AFQ.tractography' (/home/neo/anaconda3/envs/python3.9/lib/python3.9/site-packages/AFQ/tractography/__init__.py)"

**Comment by arokem** [comment]
Hello! Thanks for reporting this. We'll need a bit more information to help sort this out. 

Could you please tell us: 

1. Operating system? Looks like linux from the information you provided, but want to make sure.
2. How did you install pyAFQ? From the source-code? Using pip? 
3. Are there any previous installations of pyAFQ on this system? This kind of thing might happen when there are multiple different versions installed and they conflict with each other.
