### ISSUE TITLE
Mahalanobis diatance error

### ISSUE THREAD

**Issue by 66RuixiZheng** [yeatmanlab/pyAFQ#1066]
Why the covariance matrix used to compute the Mahalanobis Distance uses only the upper triangular matrix？
![QQ截图20231123212617](https://github.com/yeatmanlab/pyAFQ/assets/103931298/d3ed4e55-86d9-422f-b4e9-619aeb211b1c)

**Comment by 66RuixiZheng** [comment]
Based on the mathematical formula for calculating the Mahalanobis distance, the entire covariance matrix should be used.

**Comment by 36000** [comment]
@arokem this is from the code we have had from a while and is also in dipy. I am honestly not sure why we do this? Do you know why?

**Comment by arokem** [comment]
I am not 100% sure myself, but I am guessing it has to do with this piece of code in the Matlab AFQ: https://github.com/yeatmanlab/AFQ/blob/2df10b9cd1ea218ffd257485c1ea0a148c4ac273/functions/AFQ_ParamaterizeTractShape.m#L92-L95

**Comment by 36000** [comment]
Well, now I am even more confused. Let me open a PR request which does this the right way. it will get different results from the current way we do it.

**Comment by arokem** [comment]
Yes, please do. BTW: The OP points to code that has changed since, but this particular aspect is still unchanged, IIUC.

**Comment by arokem** [comment]
Closed through #1067
