### ISSUE TITLE
Possible upgrade to fury 0.9.0 in future release?

### ISSUE THREAD

**Issue by chiuhoward** [yeatmanlab/pyAFQ#1079]
I am working on generating montages of different tracts, and I can insert labels using Pillow. 

However, I was also thinking about whether it would be useful to be able to caption the original outputs of pyAFQ if the user is exporting directly in png without Pillow. In that case, being able to specify the direction of the fury `actor.vector_text` would be helpful so that they can rotate the camera in the scene and still retain proper alignment of the text labels. 

https://github.com/fury-gl/fury/issues/856

**Comment by arokem** [comment]
Close through #1080
