### ISSUE TITLE
Question about a custom bundle

### ISSUE THREAD

**Issue by htakemur** [yeatmanlab/pyAFQ#1155]
Hi all,

I am relatively new to pyAFQ and therefore I need to ask some naive question. 
pyAFQ is currently working well in my computing environment to identify default bundles. 

In addition to the default bundle,  I also have some custom bundles identified by using MRTrix3 ROI-to-ROI tracking.

I have two questions:  

- Is it possible to apply tract cleaning (like matlab AFQ has done with some parameters) for custom bundle using pyAFQ? 

- How can we use the same tract profile calculation as we have done for default major bundles for custom bundles?

**Comment by chiuhoward** [comment]
Hello Hiromasa, welcome to pyAFQ! 

You can define the cleaning parameters by passing the desired values into the dictionary when calling your AFQ object. The cleaning parameters are nested within the segmentation parameters. The API reference for this can be found here (https://yeatmanlab.github.io/pyAFQ/reference/api/AFQ/segmentation/index.html#AFQ.segmentation.clean_bundle) and I have provided some simplified code below as an example.

```
myafq = GroupAFQ(
    segmentation_params={
        "cleaning_params": {
            'distance_threshold': [integer],
            'length_threshold': [integer],
            'clean_rounds': [integer]
        }
    }
)

myafq.export_all()
```

The tract profile calculation should be done automatically by pyAFQ as long as the bundles are defined within your bundle dictionary.

Hope this helps!

**Comment by mayayab** [comment]
I think the question was about importing a tract that had already been segmented by mrTrix, not defining a custom bundle in pyAFQ. In Matlab AFQ you could add a fiber group and just apply or re-apply the cleaning and profile generation. I am not sure what the bundle dictionary would look like for that scenario in pyAFQ and if it's possible at all. Curious to follow this thread and see what the developers answer!

**Comment by arokem** [comment]
I haven't tried this myself, but I believe that you can do something like: 

```
from AFQ.recognition.cleaning import clean_bundle 
from dipy.io.streamline import load_tractogram
tg = load_tractogram("/path/to/bundle.tck", "path/to/dwi.nii.gz") # The second input is used as a spatial reference
clean_tg = clean_bundle(tg)
save_tractogram(clean_tg, "path/to/clean_bundle.tck")
```
The one thing that you might need to worry about is whether all the streamlines in the bundle are oriented the same way (i.e., they all start in ROI1 and end in ROI2), and I don't know if mrtrix takes care of that. If they are not, or if you are not sure, you need to do a few things more, which are outlined in this tutorial: https://github.com/dipy/dipy/blob/master/doc/examples/afq_tract_profiles.py, and that tutorial also shows how to calculate tract profiles from these bundles.

**Comment by htakemur** [comment]
Hi all,
Thank you very much for your responses! I greatly appreciate it. 
I tried to execute the following code

`import os
import os.path as op
import nibabel as nib
import pandas as pd
from AFQ.segmentation import clean_bundle 
from dipy.io.streamline import load_tractogram, save_tractogram
# Define a list of subject IDs
subject_ids = [100206]
for subject_id in subject_ids:
    #print(f"Processing {subject_ids})
    bids_path = op.join('/fileserver/project/proj_HCP', str(subject_id))
    dwi_path = op.join(bids_path, 'dt6', 'dwi_b2000_aligned_trilin_noMEC.nii.gz')
    custom_bundle_path_1 = op.join(bids_path, 'mrtrix3', 'LNacc_LAntinsular_wmmask_1000_candidate_JL.tck')
    fg_L = load_tractogram(custom_bundle_path_1, dwi_path) # The second input is used as a spatial reference
    clean_fgL = clean_bundle(fg_L, n_points=100, clean_rounds=1)
    custom_bundle_save = op.join(bids_path, 'mrtrix3', 'LNacc_LAntinsular_wmmask_1000_candidate_JL_cleanpyAFQ.tck')
    save_tractogram(clean_fgL, custom_bundle_save)
    custom_bundle_path_1 = op.join(bids_path, 'mrtrix3', 'RNacc_RAntinsular_wmmask_1000_candidate_JL.tck')
    fg_R = load_tractogram(custom_bundle_path_1, dwi_path) # The second input is used as a spatial reference
    clean_fgR = clean_bundle(fg_R, n_points=100, clean_rounds=1)
    custom_bundle_save = op.join(bids_path, 'mrtrix3', 'RNacc_RAntinsular_wmmask_1000_candidate_JL_cleanpyAFQ.tck')
    save_tractogram(clean_fgR, custom_bundle_save)
`

I got the following error message:

`2024-08-27 16:49:11,260 [ WARNING] Using a StatefulTractogram as reference, this will copy only the space_attributes, not the state. The variables space and origin must be specified separately.
2024-08-27 16:49:11,260 [ WARNING] To copy the state from another StatefulTractogram you may want to use the function from_sft (static function of the StatefulTractogram).
2024-08-27 16:49:11,265 [   ERROR] Voxel space values lower than 0.0.
Traceback (most recent call last):
  File "/fileserver/project/proj_HCP/script/pyAFQ_custombundle/s_NAccbundle_clean.py", line 18, in <module>
    save_tractogram(clean_fgL, custom_bundle_save)
  File "/home/htakemur/anaconda3/lib/python3.9/site-packages/dipy/io/streamline.py", line 43, in save_tractogram
    raise ValueError('Bounding box is not valid in voxel space, cannot '
ValueError: Bounding box is not valid in voxel space, cannot load a valid file if some coordinates are invalid.
Please set bbox_valid_check to False and then use the function remove_invalid_streamlines to discard invalid streamlines.`

It looks like some coordinate mismatch and reference nifti data but I don't know how to resolve it. 

Do you have any thoughts on what to check, in order to narrow down the possible sources of this error?

**Comment by htakemur** [comment]
Hello @arokem! 

Thank you very much for your help! 
The code worked out without an error by adding changes you suggested.

However, it looks like that export tck file has some coordinate mismatch... 

In the following image, the red is an original tck and blue is an output with cleaning. 

![pyAFQ_cleanbundlecoordinate](https://github.com/user-attachments/assets/8b627ec5-3bd7-4fcf-91ab-42d811996fe9)

Do you have any thoughts on how to limit the possibilities on what is the source of this error?

**Comment by 36000** [comment]
I think I found the problem. I am assuming Voxel space when handling the StatefulTractograms in clean_bundle. I will make a PR to fix this. In the mean time, I think this should fix it:
```
from dipy.io.stateful_tractogram import Space
load_tractogram(custom_bundle_path_1, dwi_path, Space.VOX)
```
No need to change any other lines of the code. If this does not fix it, let me know.

**Comment by htakemur** [comment]
Thank you very much, @36000 ! 
The problem of coordinate mismatch is resolved. In the next step, I will try to test tractometry on the custom bundle following the tutorial @arokem pointed out...

**Comment by arokem** [comment]
I'll close this for now, but feel free to reopen if this recurs.
