### ISSUE TITLE
Find all the calls to `get_data` and change them to `get_fdata`

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#117]
https://github.com/yeatmanlab/pyAFQ/blob/16f8c565dc8e60b6928664e1a648aff4bcccecc9/AFQ/segmentation.py#L284

**Comment by richford** [comment]
Hah, this is ridiculous timing but I was just looking at this earlier.

BTW, putting
```
[alias]
    sed = !sh -c 'git grep --null --full-name --name-only --perl-regexp -e \"$1\" | xargs -0 perl -i -p -e \"s/$1/$2/g\"' -
```
in `.gitconfig` makes this really easy with `git sed get_data get_fdata`.

**Comment by arokem** [comment]
Yeah, John and I were looking at this together and he noticed this discrepancy. Thanks for the sed tip. Very useful!
