### ISSUE TITLE
Rotate b-vectors according to the registration

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#135]
Rotate the b-vectors in this function

https://github.com/yeatmanlab/pyAFQ/blob/f057b5c7e7297a738044977a00eee505da212dab/AFQ/registration.py#L390

Use: https://github.com/nipy/dipy/blob/master/dipy/core/gradients.py#L449

**Comment by arokem** [comment]
Assigned to @36000

**Comment by 36000** [comment]
Let dipy handle this
