### ISSUE TITLE
Segmentation of mtrix-generated CSD tractography?

### ISSUE THREAD

**Issue by lucindasisk** [yeatmanlab/pyAFQ#147]
Hi @arokem ! So excited about pyAFQ. Wondering if there is a way to feed in multishell ODF data processed using mrtrix (CSD; iFOD2 algorithm) for automated tract segmentation and quantification using the AFQ algorithm? Would be amazing to be able to do so, and apologies if I missed this in the documentation. Thanks for your time!

**Comment by arokem** [comment]
Hi @lucindasisk! It should be possible to plug in your own tracks, provided they are saved in the .trk format. For now, the way to do that would be to use the [example](https://github.com/yeatmanlab/pyAFQ/blob/master/examples/plot_tract_profile.py) and replace the tractography bit with reading your file (like [so](https://github.com/yeatmanlab/pyAFQ/blob/master/examples/plot_tract_profile.py#L97))

**Comment by lucindasisk** [comment]
Awesome, thank you so much!

**Comment by arokem** [comment]
Let us know how this goes! 

I'll leave this open with the "documentation" label, until we have an example, or documentation page that shows exactly how to do this.

**Comment by 36000** [comment]
Moved to #434
