### ISSUE TITLE
Make s3fs_nifti_read compatible with non-gzipped files

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#151]
This currently doesn't work raising something like: 

```
MNI_T2_img = afd.s3fs_nifti_read('hcp.recobundles/mni_icbm152_t2_tal_nlin_asym_09a.nii')
File "/usr/local/lib/python3.7/site-packages/AFQ/data.py", line 547, in s3fs_nifti_read
rr = zz.read()
File "/usr/local/lib/python3.7/gzip.py", line 276, in read
return self._buffer.read(size)
File "/usr/local/lib/python3.7/gzip.py", line 463, in read
if not self._read_gzip_header():
File "/usr/local/lib/python3.7/gzip.py", line 411, in _read_gzip_header
raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\\\x01')
```

I tried to make it compatible [here](https://github.com/yeatmanlab/pyAFQ/pull/150/commits/4baced84ba4af61602a6e78121f2a08fa77808e9), but that didn't work (I think -- raising the same error). It's not central to what I am doing right now, so I am just leaving this note here, so we remember to come back to it at some point.

**Comment by 36000** [comment]
no longer relevant here
