### ISSUE TITLE
Do we really need the entire nib.Nifti1Image object here?

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#153]
https://github.com/yeatmanlab/pyAFQ/blob/679e724929158bdbe2a29cc355b7ede22bae45ae/AFQ/segmentation.py#L279

I suspect that if the  mapping has already been calculated  in advance, we really only need the affine at this point, which could save some time/memory when done in a distributed fashion, because we could read it once on the user node  and send the 4-by-4 around to the worker nodes, instead of  having  every node read this from the  nifti file.

**Comment by 36000** [comment]
I agree. If you already have the mapping, you only need the affine. Let me make a pull request, I will re-arrange things so that if the user gives an affine and a mapping, the img is not needed.

**Comment by arokem** [comment]
Closed by #154
