### ISSUE TITLE
Add selection based on cortical endpoints

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#168]
See `AFQ_DefineFgEndpoints` in the  Matlab implementation

**Comment by jyeatman** [comment]
The simplest thing to do here would be to use the exact same template as we do in the matlab version. Then we could have an option to use freesurfer instead

**Comment by arokem** [comment]
Yes. That's what I was thinking of doing as a first pass.

Based on [this line](https://github.com/yeatmanlab/AFQ/blob/50bdc81e060670a83789a4168f9b5e88cea39c2a/functions/AFQ_DefineFgEndpoints.m#L98) it should be this file:  https://github.com/yeatmanlab/AFQ/blob/50bdc81e060670a83789a4168f9b5e88cea39c2a/templates/labelMaps/MNI_AAL_AndMore.nii.gz, correct? What's the difference between that one and this one: https://github.com/yeatmanlab/AFQ/blob/50bdc81e060670a83789a4168f9b5e88cea39c2a/templates/labelMaps/MNI_AAL.nii.gz?

**Comment by jyeatman** [comment]
I think that is correct. But I don't know what the difference is.Beyond the fact that one has AAL And More!

**Comment by arokem** [comment]
More definitely sounds better! Let me see if I can at least have a poke at this code, so that I might have some informed questions to ask on Monday's call.

**Comment by arokem** [comment]
@jyeatman : question about the implementation. [This section of code](https://github.com/yeatmanlab/AFQ/blob/50bdc81e060670a83789a4168f9b5e88cea39c2a/functions/AFQ_DefineFgEndpoints.m#L54-L63) suggests that enpoint location for each bundle is determined based on an ordering within a list. For example, based on the  strings stored here, it looks like number 3 and 4 are the corticospinal tracts. Where is the list with the ordering of all 20 stored? Is it correct to assume that [this](https://github.com/yeatmanlab/AFQ/blob/50bdc81e060670a83789a4168f9b5e88cea39c2a/functions/AFQ_SegmentFiberGroups.m#L199-L208) is the ordering used here as well?

**Comment by jyeatman** [comment]
Not sure I fully understand. But, the default behavior of afq is to segment 20 fiber groups. This segmentation is always done in the same order. Then it looks up the endpoint regions corresponding to each fiber group. The ordering of fiber groups is defined in the function you note.
1. Left Thalamic Radiation
2. Right Thalamic Radiation
3. Left Corticospinal
4. Right Corticospinal
5. Left Cingulum Cingulate
6. Right Cingulum Cingulate
7. Left Cingulum Hippocampus
8. Right Cingulum Hippocampus
9. Callosum Forceps Majo
10. Callosum Forceps Minor'
11. Left IFOF
12. Right IFOF
 13. Left ILF
14. Right ILF
15. Left SLF
16. Right SLF
17. Left Uncinate
18. Right Uncinate
19. Left Arcuate
20. Right Arcuate

**Comment by arokem** [comment]
Yep - that answers my question - and conforms to what I assumed. Now almost
done in #183.

**Comment by arokem** [comment]
Implemented in #183
