### ISSUE TITLE
pyAFQ template

### ISSUE THREAD

**Issue by Qji12** [yeatmanlab/pyAFQ#174]
Hi 
Thanks for resolving issue# 172. I found that in ./AFQ_data, the roi files and prob maps are not consistent: prob [197 233 189], roi [182 218 182], MNI template [197 233 189]. Is that a problem when you trying to warp roi? Thanks

**Comment by arokem** [comment]
It might be. I am still looking into it. I think that https://github.com/yeatmanlab/pyAFQ/pull/183/commits/b4f1a7a493d6204cded47235965d978f45c9e672 might resolve this.

**Comment by arokem** [comment]
I believe this is resolved in #183. Let me know if you run into any issues.
