### ISSUE TITLE
New feature: bundles object

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#176]
This would hold the contents of the output of segmentation and would know about the space in which the streamlines are stored (like a StatefulTractogram object), but would also know about the identity of the  bundles that resulted in the segmentation. Might also have a `clean` method, a `bundle_profiles` method (that takes a volume and optionally an affine and returns the profiles) and so on.

**Comment by arokem** [comment]
Currently WIP in #184

**Comment by 36000** [comment]
We have other issues about integrating this, but the object itself has been made.
