### ISSUE TITLE
plot_tract_profile example errors

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#188]
Hi!

I'm trying to run the example and getting the following error:

```bash
$ time python ./plot_tract_profile.py
/home/users/gkiar/ace_mount/ace_home/code/env/gp3/lib/python3.6/site-packages/dipy/stats/__init__.py:7: UserWarning: The `dipy.stats` module is still under heavy development and functionality, as well as the API is likely to change in future versions of the software
  warnings.warn(w_string)
Dataset is already in place. If you want to fetch it again please first remove the folder /home/users/gkiar/.dipy/stanford_hardi 
Calculating DTI...
Tracking...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:15<00:00,  6.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 652536/652536 [3:55:01<00:00, 46.28it/s]
Traceback (most recent call last):
  File "/home/users/gkiar/plot_tract_profile.py", line 47, in <module>
    aus.write_trk('./dti_streamlines.trk', streamlines, affine=img.affine)
  File "/home/users/gkiar/ace_mount/ace_home/code/env/gp3/lib/python3.6/site-packages/AFQ/utils/streamlines.py", line 28, in write_trk
    streamlines = dtu.move_streamlines(streamlines, affine)
AttributeError: module 'dipy.tracking.utils' has no attribute 'move_streamlines'

real    235m34.280s
user    172m31.158s
sys     63m1.843s
```

Thanks!

**Comment by arokem** [comment]
Are you running the current `master` branch? I believe this is fixed in
`master`

**Comment by gkiar** [comment]
If `master` is the default branch, then yes. I installed it yesterday (December 9th at 13h29 EST) using the following command:

```bash
$ pip install git+https://github.com/yeatmanlab/pyAFQ.git
```

The version is 0.1.dev0.

**Comment by arokem** [comment]
Did you change the `plot_tract_profile.py` script? The error you are getting is on line 47 of that script and this is the current l47: https://github.com/yeatmanlab/pyAFQ/blob/master/examples/plot_tract_profile.py#L47

**Comment by gkiar** [comment]
Ah, it appears that the [link from the documentation](http://yeatmanlab.github.io/pyAFQ/auto_examples/plot_tract_profile.html) doesn't give the up to date script, and that is where I downloaded the script from. Will try using the one in the repo

**Comment by arokem** [comment]
Gotcha. Yes - we should update that. I'll leave this open for now, to
remind me to update that as soon as #183 lands.

**Comment by gkiar** [comment]
Success! And ***so*** much faster, too... Timing once the data was downloaded:

```bash
real    0m32.516s
user    0m44.594s
sys     0m17.240s
```

**Comment by 36000** [comment]
@arokem we should come up with a system to update these examples automatically from the code.

**Comment by arokem** [comment]
The examples on our website update every time we make a release. So, people installing from PyPI will get examples that sync up with their installation. Folks installing from GitHub (like @gkiar did here) might find the examples sometimes out of sync with master. I think that it's fine. And I think that we can close this one.
