### ISSUE TITLE
'move_streamlines' not found in dipy.tracking.utils

### ISSUE THREAD

**Issue by eloydelas** [yeatmanlab/pyAFQ#200]
Hi,

We have been working with pyAFQ during a long period. Lamentably, we installed AFQ again but the following error appears: AttributeError: module 'dipy.tracking.utils' has no attribute 'move_streamlines'

One we checked the error, we realized that the move_streamlines() was deleted in dipy 1.0. Any suggestion on how to solve this problem?

Cheers,

Eloy

**Comment by arokem** [comment]
Hi Eloy -- first of all: happy to hear that this has been useful! And thanks for reporting this. Regarding the issue you are facing: it would be very hard for us to support use of both 0.X and 1.X versions of DIPY, so we've decided to move on to the new version. The current version of pyAFQ should support DIPY 1.X, so updating pyAFQ should resolve this. We now have a 0.1 out on pypi, so you should be able to install it using a `pip install --upgrade pyAFQ` or from the current `master` branch. Please let me know how  you  get on!

**Comment by eloydelas** [comment]
Hi Ariel, thanks for the quick response!!+ we have implemented the new version of DIPY and it works perfectly. 
Best wishes for 2020,
Eloy

**Comment by arokem** [comment]
Great. Let us know if you run into any issues with the new version. Closing.
