### ISSUE TITLE
Should we find a skull-stripped MNI template for alignment/registration?

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#210]
The skull is usually just barely visible in B0 images, but is very clearly visible in the MNI template we are currently using.

**Comment by 36000** [comment]
From left to right: b0 transformed to mni, b0 transformed to mni without prealign, and mni template
![image](https://user-images.githubusercontent.com/9562159/74066760-a0406a00-49ac-11ea-93bc-6397d94eb544.png)

**Comment by arokem** [comment]
It looks like non-linear registration is  indeed stretching the brain down into parts of the image that contain skull and other non-brain stuff. 

It looks like templateflow might have what we need: the T2w + a brain mask.

**Comment by arokem** [comment]
We can use templateflow with a mask: https://github.com/templateflow/python-client/issues/34

**Comment by 36000** [comment]
Closed by #224 .
