### ISSUE TITLE
b0_threshold being looked for in files, rather than segmentation section of config file

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#216]
Currently the `b0_threshold` value is looked for in the `files` portion of the provided `.toml` file, rather than the `segmentation` section where it is described and specified as a possible argument.

https://github.com/yeatmanlab/pyAFQ/blob/6559a8094bf52132269483b229692dcd72a3feb9/bin/pyAFQ#L128

**Comment by arokem** [comment]
This was resolved in #206
