### ISSUE TITLE
Can't see pipeline outputs?

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#219]
Where are the derivatives stored? After a partial run that crashed several steps in I was unable to find them... Is there a way to specify an output directory?

**Comment by arokem** [comment]
We currently store the derivatives under `'study/derivatives/afq'`. Are you not seeing your files there?

**Comment by arokem** [comment]
Can I close this? Did you find your derivatives?

**Comment by gkiar** [comment]
Hmm... Nope, my derivatives definitely didn't show up there. I'll see if I can replicate the problem trying again.
