### ISSUE TITLE
Enable caching of previous derivatives?

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#220]
Is there an option to either use or ignore existing derivatives found inside the target output directory (crossref: #219)? Something like `cache = True|False`, where pieces are recycled if existing but that can be turned off if we want a clean slate.

**Comment by arokem** [comment]
We used to have a `force_recompute` key-word argument in the API module, but it added a lot of complexity to the code. Maybe we should revisit?

**Comment by arokem** [comment]
Per default, we do not over-write outputs if they already exist. #207 implements a `force_recompute` key-word argument and #225 implements a config option for the CLI that allow over-riding this default, and recompute everything.

**Comment by 36000** [comment]
Moved to #406
