### ISSUE TITLE
expected data type for diffusion images?

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#221]
My default diffusion images (like most out of an MRI machine) are int16. However, after processing these with `eddy` and other typical FSL tools, they are converted to `float32` by default. For the sake of space (and having `gzip` compression be useful), I'd like to convert my data back to `int16`.

Does `pyAFQ` care about the data type of my diffusion images?

**Comment by arokem** [comment]
No - I think that should be fine.
