### ISSUE TITLE
DWI registration needs more work

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#23]
In particular, need to rotate the b vectors according to the affine transformations derived from the registration.

**Comment by richford** [comment]
@arokem: Was this resolved or should we keep this open?

**Comment by arokem** [comment]
Let's keep it around. I think that I put this here because there were some
concrete use-cases where this didn't work very well. But I don't exactly
remember what they were.

Either way, actually tackling this one is probably rather low priority.

**Comment by arokem** [comment]
This is handled in https://github.com/akeshavan/preafq
