### ISSUE TITLE
Use FA template for alignment

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#243]
There's a nice-looking MNI-registered FA template here: https://www.fmrib.ox.ac.uk/ukbiobank/

**Comment by 36000** [comment]
To get the FA map you have to download this zip file: http://biobank.ctsu.ox.ac.uk/showcase/refer.cgi?id=9028
It is 1 GB. The dti_FA is only 8.2 MB. I don't know if there is a practical way to only get the dti_FA file.

**Comment by arokem** [comment]
Ugh. I wonder if they'd let us mirror just that one file somewhere else. Let me see who we need to email to ask.

**Comment by 36000** [comment]
It's possible there is a hacky way to access that large file and use .zip's internal file system to only download the FA map.

**Comment by 36000** [comment]
The FA map from that source should also be stripped of its spinal cord (optionally?)
