### ISSUE TITLE
Problem in Endpoints filtering step

### ISSUE THREAD

**Issue by pietroastolfi** [yeatmanlab/pyAFQ#256]
The segmentation seems to work in the first step, waypoints rois filtering, but it produces a strange behaviour in the second step, endpoints filtering, where some tracts like ATR have a huge drop in terms of number of streamlines. 
I looked into detail on the reason of this drop, by saving the endpoints AAL rois corresponding to the ATR_L, and overlapping it with the segmentation produced by AFQ without endpoints filtering.
The results is here in figure:
<img width="412" alt="ATR_eP_filter_error" src="https://user-images.githubusercontent.com/15109253/80922167-7a441f00-8d7b-11ea-9dde-4bda24695164.png">
It's clear that the AAL region used for this filtering is taken from the wrong emisphere.

**Comment by arokem** [comment]
Thanks for reporting this @pietroastolfi! What version of pyAFQ are you using? Is it possible that this is resolved in the recently-released version 0.3 (see https://github.com/yeatmanlab/pyAFQ/pull/237/commits/0eb99a8bc33412a3d026f488ce62557890de074a)?

**Comment by pietroastolfi** [comment]
The version is: 0.3.dev7465745204 installed with pip+git in a dedicated conda environment. I don't know to which commit this build refers to. I can do a trial updating.

**Comment by arokem** [comment]
If you could try to run this with current master, that would be
really helpful.

**Comment by 36000** [comment]
This may have been fixed in #283. would be good to try again with version 0.4 or master. nice find!

**Comment by 36000** [comment]
This was fixed in #283 , good find!
