### ISSUE TITLE
Can't import AFQ with python3

### ISSUE THREAD

**Issue by soichih** [yeatmanlab/pyAFQ#267]
I have a following test code

```
#!/usr/bin/python3
from AFQ import api 
```

When I run this, I ran into the following error message.

```
Traceback (most recent call last):
  File "./segment-afq.py", line 2, in <module>
    from AFQ import api
  File "/usr/local/lib/python3.6/dist-packages/AFQ/__init__.py", line 1, in <module>
    from .data import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/AFQ/data.py", line 15, in <module>
    from templateflow import api as tflow
  File "/usr/local/lib/python3.6/dist-packages/templateflow/api.py", line 6, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD
  File "/usr/local/lib/python3.6/dist-packages/templateflow/conf/__init__.py", line 81, in <module>
    ignore=['.git', '.datalad', '.gitannex', '.gitattributes', 'scripts'])
  File "/usr/local/lib/python3.6/dist-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/lib/python3.6/dist-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 804: ordinal not in range(128)

```

I am not sure if this is my python3 installation issue, or pyAFQ issue, or maybe templateflow issue.. Could you help me troubleshoot this problem?

I am running pyAFQ Docker container with the following Dockerfile through singularity 3.5.2

```
FROM ubuntu:18.04

MAINTAINER Brad Caron

RUN apt-get update && apt-get -y install \
    python3 \
    python3-pip \
    jq \
    time \
    git \
    curl \
    unzip \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl-dev

RUN pip3 install setuptools_scm 
RUN pip3 install git+git://github.com/yeatmanlab/pyAFQ.git@master#egg=pyAFQ

ENV SINGULARITYENV_PYTHONNOUSERSITE=true


```

**Comment by arokem** [comment]
Thanks for reporting! 

I can reproduce this on docker (but mystified as to why we don't see this in the CI). I think that this is a templateflow (or possibly pybids?) thing. Maybe in interaction with the OS version?

For example, using the following Dockerfile: 

```
FROM ubuntu:18.04

RUN apt-get update && apt-get -y install \
    python3 \
    python3-pip \
    jq \
    time \
    git \
    curl \
    unzip \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl-dev

RUN pip3 install templateflow
```
built with (sorry, no singularity here, but I don't think that matters): 

```
docker build . -t arokem/tflow_test:0.02
```

And running 

```
docker run -it arokem/tflow_test:0.01 python3 -c"from templateflow import API"
```

produces the same error. I'll report this on the templateflow repo.

**Comment by arokem** [comment]
Whoops. See comment on the templateflow issue. 

Running `docker run -it arokem/tflow_test:0.02 python3 -c"from templateflow import api"` (with the right version of the image ... ) does not result in this error. I think this means we have some weird conflict in versions between the dependencies for pyAFQ.

**Comment by soichih** [comment]
It looks like Docker's official python container uses Debian 10. 

I've replaced `FROM ubuntu` with `FROM python:3.6`, but I am still seeing the same error message.

But I did make a few other changes to my Dockerfile
```
FROM python:3.6

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install sudo python3.6 python3-pip jq time git curl unzip
RUN pip3 install pyAFQ
```

(I decided to install it pyAFQ using pip - instead of using github/master branch for pyAFQ.)

Here is the error message.

```
/usr/local/lib/python3.6/site-packages/dipy/stats/__init__.py:7: UserWarning: The `dipy.stats` module is still under heavy development and functionality, as well as the API is likely to change in future versions of the software
  warnings.warn(w_string)
Traceback (most recent call last):
  File "./segment-afq.py", line 16, in <module>
    from AFQ import api
  File "/usr/local/lib/python3.6/site-packages/AFQ/__init__.py", line 1, in <module>
    from .data import *  # noqa
  File "/usr/local/lib/python3.6/site-packages/AFQ/data.py", line 15, in <module>
    from templateflow import api as tflow
  File "/usr/local/lib/python3.6/site-packages/templateflow/api.py", line 6, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD
  File "/usr/local/lib/python3.6/site-packages/templateflow/conf/__init__.py", line 81, in <module>
    ignore=['.git', '.datalad', '.gitannex', '.gitattributes', 'scripts'])
  File "/usr/local/lib/python3.6/site-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/lib/python3.6/site-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/local/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 804: ordinal not in range(128)
failed
```

Could you try my Dockerfile and see if you can recreate the problem?

**Comment by arokem** [comment]
Are you sure you are running from the right version of the image? I don't get this error when I build from this Dockerfile.

**Comment by soichih** [comment]
Oh I think it works when I run it via docker but not through singularity.

I have to run it like this..

```
singularity exec -e docker://brainlife/pyafq:1.0 ./afqcode.py
```

I will do more troubleshooting tomorrow.. but please let me know if you know why it wouldn't work via singularity.

**Comment by arokem** [comment]
Hey @soichih : sorry for dropping the ball here. I have no idea why this would work in docker, but not singularity. Did you figure it out on your end?

**Comment by soichih** [comment]
@arokem 

I did a bit more troubleshooting on this and I was able to resolve this by adding the following Dockerfile entries

```
RUN apt-get install -y locales
RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && echo "LANG=en_US.UTF-8" > /etc/locale.conf && locale-gen en_US.UTF-8
ENV LC_CTYPE="en_US.UTF-8"
```

It basically installs the en_US.UTF-8 locale into the container, and set the LC_TYPE so that python interpreter will use that local instead of the default "ascii" encoder.

**Comment by arokem** [comment]
Thanks for following up here! I wonder whether we can simplify this by consistently applying https://www.python.org/dev/peps/pep-0263/

**Comment by 36000** [comment]
This is probably the similar issue to : https://github.com/bids-standard/pybids/issues/69 with a similar solution.
In other words, pybids should add `encoding='utf-8' ` to the call to open that handle. I will open an issue there, and see what they think.

**Comment by 36000** [comment]
This should be solved in the next pyBIDS release. I will leave this issue open to remind us to update our requirements.
