### ISSUE TITLE
Segmentation trk file name changes

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#278]
Currently the only difference between the streamlines saved after segmentation and before is that afterwards we specify the segmentation algorithm: https://github.com/yeatmanlab/pyAFQ/blob/f4b9ec2beb6215f8d249e379a75983d4f83e56c7/AFQ/api.py#L771
This is confusing. We should add "segmented" or something like that to the filenames for segmented and cleaned trk files.

**Comment by arokem** [comment]
The reason for this is that we are trying to remain BIDS-compliant. 

Unfortunately, there still isn't a fully-fleshed out definition for how to store tractography segmentations (see [here](https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/06-diffusion-derivatives.html) for the current draft of the BIDS diffusion derivatives). As I understand it, we're only allowed one suffix (here `_tractography`) and I've tried to put other descriptors, such as tractography algorithm and segmentation into the `desc-` field). Maybe we should use the `subset` field for this (see [here](https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/06-diffusion-derivatives.html#describing-tractography)), where `subset_bundles` is the subset that contains all bundles and `subset_L_ARC` is the subset that contains just the left arcuate (and so forth)?
