### ISSUE TITLE
Quantifying lateralization

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#298]
Lateralization could be an important metric not necessarily captured by FA or MD. An example of the effects of lateralization is shown here: https://www.pnas.org/content/104/43/17163

How could we quantify this? 

One idea is to fit an ellipsoid to the voxels covered by resampled streamlines from a given bundle.

**Comment by arokem** [comment]
There are two separate things here. One is lateralization. We can calculate that in every node of every bundle that has symmetry using something like a contrast index. 

LI = (left – right)/(left + right) 

Where "left" is a scalar(e.g., FA) measured in a specific node in a specific bundle, and "right" is the same scalar in the equivalent node in the corresponding node on the other hemisphere. This provides a contrast index that is (arbitrarily) larger than 0 for left-lateralized nodes/scalars (i.e., larger on the left) aand smaller than 0 for right-lateralized nodes/scalare. See for example our previous work using this index: https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.24626  This would be good to calculate. 

The other is the calculation of bundle volume or bundle cross-section, if calculated as a tract profile. @jyeatman : how would you recommend calculating bundle volume as a tract profile? I have a feeling you have done this before.

**Comment by jyeatman** [comment]
Indeed I have. First I will say that volume is noisy. I haven't come to a
measure I love. But there are a couple implemented in AFQ.
1) Volume based on the covariance matrix at each node. The
covariance matrix gets calculated for the sake of weighting fiber. You can
calculate volume as a function of the determinate. Basically the volume of
the ellipsoid defined by the covariance matrix.
2) Unique coordinates at each node.

I think the second is probably preferable. You could also allow for a
threshold on number 2 where you only count coordinates with at least n
fibers. Both are implemented here:
https://github.com/yeatmanlab/AFQ/blob/master/functions/AFQ_TractProfileVolume.m
