### ISSUE TITLE
Make it possible to install with pip without the editable option

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#306]
This was introduced in #289 (https://github.com/yeatmanlab/pyAFQ/commit/168b78cd882ad8f69f5b4613b1e49c1b3ebaa613), but we probably want to undo that. See discussion here: https://github.com/yeatmanlab/pyAFQ/pull/289#discussion_r451125585

**Comment by 36000** [comment]
Fixed in #320
