### ISSUE TITLE
Compare CSVs

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#313]
There should be a viz function whose inputs are two csv's and which generates an image similar to that created by plot_tract_profiles but with two lines in each plot. It should also output the percent differences, possibly beneath each plot.

**Comment by arokem** [comment]
Small comment: I generally prefer to use a contrast index: 

(A-B) / (A+B) 

over percent difference: 

(A - B) / B

That's because they are symmetrical with respect to the choice of the baseline for comparison (whether we compare to A or B won't change the magnitude).
