### ISSUE TITLE
Use SyN registration in recobundles

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#316]
Currently, recobundles uses an affine transformation based on SLR to a whole-brain tractography in MNI template space (the `'hcp_atlas'`). But there is an alternative: we could compute a SyN registration of the diffusion data to the MNI space and then apply this non-linear transform to the streamlines, to get them into the MNI space, before then using the template space bundles as references. I started trying to implement this in #144, but it needs more work.

**Comment by 36000** [comment]
Done.
