### ISSUE TITLE
Connectivity Matrix

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#328]
There should be an API function that outputs a connectivity matrix from the tractography given some template: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4361080/

**Comment by arokem** [comment]
This is an interesting idea and I realize that many users might want something like this, but there are many issues with how you would select what to include in such a connectivity matrix of this sort, so I would rather just declare this out of scope for pyAFQ and refer interested users to [DIPY functions that create such matrices](https://dipy.org/documentation/1.0.0./examples_built/streamline_tools/).
