### ISSUE TITLE
Allow input tractography from other derivative pipelines

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#336]
Right now, if you want pyAFQ to pick up tractography that was generated through another pipeline, you would have to copy it into the folder for each subject in the right time. It would be good if the API allowed us to specify the name of a pipeline (like we currently have `dmriprep` and `segmentation`) to pick up tractography products.

**Comment by richford** [comment]
This is potentially a good candidate for the 2020 code sprint since it is on the critical path to our previously discussed tractography comparison project. Either way, I'd be interested in working on this to move that project forward.

**Comment by 36000** [comment]
Resolved by #422
