### ISSUE TITLE
Visualization with plotly hangs

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#349]
I am reanalyzing the data from #261. 

The first comment I have is that the issues raised there seem to be resolved on master, which is great!

This issue has to do with the observation I made along the way that plotly seems to hang or get stuck while visualizing. I am not sure what the cause is, but it doesn't seem to be random: I tried running this a few times and it always seems to hang while visualizing the second bundle it encounters (ATR_L).

Hard-quitting the program suggests that this is stuck while executing this line: https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/viz/plotly_backend.py#L245

**Comment by 36000** [comment]
Interesting. I would guess this has something to do with kaleido. I wonder if a recent version broke it: https://pypi.org/project/kaleido/#history

Or maybe it has something to do with this: https://github.com/plotly/Kaleido/issues/23
Try printing the working directory each loop and see if it changes.

**Comment by arokem** [comment]
Still haven't figured this one out, but noting that pinning kaleido to 0.0.2 does not resolve this issue.

**Comment by 36000** [comment]
I am going to try printing the working directory each loop right now.

**Comment by 36000** [comment]
Working directory change does not seem to be the problem. I hung in the 5th frame of the first gif it tried to make.

**Comment by 36000** [comment]
So I did it a little test. So, for each gif, write_image is called 60 times (once per frame). It looks like the time this call takes (time to export ) starts off high, but bearable. However, that time steadily increases untill the program stalls. I think I should setup a contained example of this and post an issue to kaleido. For this I would need a saved figure that could be posted publicly.
```
Time to export: 4.486781587824225
Time to export: 3.5240664649754763
Time to export: 3.313969453331083
Time to export: 3.2749502579681575
Time to export: 3.324021595995873
Time to export: 3.2209196309559047
Time to export: 3.303899036720395
Time to export: 3.442790257744491
Time to export: 3.4185144901275635
Time to export: 3.4022287311963737
Time to export: 3.4128747819922864
Time to export: 3.3995601208880544
Time to export: 3.518615571781993
Time to export: 3.4847019966691732
Time to export: 3.548639959190041
Time to export: 3.70137710403651
Time to export: 3.611623720731586
Time to export: 3.740179928019643
Time to export: 3.74419933790341
Time to export: 3.8939710282720625
Time to export: 3.7193696573376656
Time to export: 3.8059598891995847
Time to export: 3.9091362422332168
Time to export: 3.9675941579043865
Time to export: 3.9643540889956057
Time to export: 3.9978082166053355
Time to export: 4.318788264878094
Time to export: 4.117016344796866
Time to export: 4.111409660894424
Time to export: 4.15750822192058
Time to export: 4.079754148144275
Time to export: 4.158695610705763
Time to export: 4.243555110879242
Time to export: 4.405702090356499
Time to export: 4.467643893323839
Time to export: 4.398983582854271
Time to export: 4.470905703026801
Time to export: 4.409403616096824
Time to export: 4.741021194029599
Time to export: 4.8629144821316
Time to export: 4.643373737111688
Time to export: 4.575741484295577
Time to export: 4.617417489178479
Time to export: 4.689907547086477
Time to export: 4.629673202056438
Time to export: 4.525414559058845
Time to export: 4.8425263450481
Time to export: 4.730481673032045
Time to export: 4.7286105109378695
Time to export: 4.837432928849012
Time to export: 4.758413858246058
Time to export: 4.976214638911188
Time to export: 4.91107641486451
Time to export: 4.967634523753077
Time to export: 4.9093238902278244
Time to export: 5.002824463881552
Time to export: 5.514556035865098
```

**Comment by arokem** [comment]
It would be good to report this upstream to plotly/kaleido. For our use, one option would be to separate into two use-cases: if the user chose "fury" for the backend, we create gifs. Otherwise, if they chose "plotly", we only create HTML outputs. Does that make sense?

**Comment by 36000** [comment]
That's being done here: #361 . I will leave this open to remind me to send an issue to kaleido.
