### ISSUE TITLE
Visualizations made using CLI are streamline-less 

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#357]
I am seeing this in our GIFs (with fury backend)

![sub-01_ses-01_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_L_viz](https://user-images.githubusercontent.com/118582/90177819-f200ed00-dd5f-11ea-978c-03ae02da65a8.gif)
![sub-01_ses-01_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_R_viz](https://user-images.githubusercontent.com/118582/90177836-f75e3780-dd5f-11ea-8dd4-2024ef2300f0.gif)

But this in MI-BRAIN: 

<img width="1508" alt="Screen Shot 2020-08-13 at 12 25 15 PM" src="https://user-images.githubusercontent.com/118582/90177941-1230ac00-dd60-11ea-84eb-fdb0deb2d01f.png">

This is again with the data from #261. I wonder whether a transformation into the right space (`to_vox`, I believe) is missing somewhere.

**Comment by 36000** [comment]
It should be noted that I use the fury backend to make gif's routinely with the prek data, and, as of ~July 15th, it also works with the HCP data. So if it is a missing transformation, that transformation would have to be close to the identity in those datasets.

**Comment by arokem** [comment]
Yes. This is mystifying. Two thoughts: 

1. This could be something about a mis-specified affine in this data. 
2. This could be something about new VTK that broke the visualizations.

**Comment by 36000** [comment]
Are you looking at the clean bundles in mi-brain?

**Comment by 36000** [comment]
We output unclean bundles to bundles/ folder and clean bundles to clean_bundles/ folder.

**Comment by arokem** [comment]
Yes. These are the clean bundles in mi-brain

**Comment by arokem** [comment]
OK. Looks like this is resolved when I pin VTK to 8.1.2. #359

**Comment by 36000** [comment]
I used to have it pinned to that. I should have mentioned this. It throws a few warnings when using version 9. I think fury may have to be updated somehow. For now, though, I think VTK 8.1.2 is fine.

**Comment by arokem** [comment]
Let's leave this one open, though. As long as we can't upgrade to VTK 9, we can't support Python 3.8 (no VTK 8.1.2 on Python 3.8...)

**Comment by 36000** [comment]
I believe this could be the bug: https://github.com/fury-gl/fury/issues/254
In which case fury 0.6.0 may solve our problems (instead of reverting to VTK 8)

**Comment by arokem** [comment]
Yep. Good find!
