### ISSUE TITLE
Make outputs that can be directly opened in AFQ-Browser

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#369]
If there is participant data: a participants.tsv or participants.json file in the BIDS dataset, we can use that to generate subjects.csv. Otherwise, this will just be subject (and session?) ids. 

And we need to take our CSV file and make an AFQ-browser compliant nodes.csv.

**Comment by 36000** [comment]
We should also change the column names back to subjectID, tractID, and nodeID from our current subjectID, bundle, node.

**Comment by arokem** [comment]
Or update AFQ-Browser to take these outputs.
