### ISSUE TITLE
Consider how we sample profiles

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#379]
Sample profiles such that the same features across subjects appear at the same node.

For example, if there's a dip in the FA where that bundle crosses other bundles, that should be on the same node(s) across subjects for doing comparisons.

**Comment by 36000** [comment]
Discussion in #81 useful

**Comment by mnarayan** [comment]
Came up in discussions that application of functional alignment methods (Elastic FDA) by Wu,Srivastava could be useful to try. 

Papers:
https://projecteuclid.org/euclid.ejs/1414588162

Code
https://github.com/jdtuck/fdasrsf_python

**Comment by 36000** [comment]
pyAFQ could output multiple profiles, one for each alignment

**Comment by 36000** [comment]
Likely better handled post-pyAFQ
