### ISSUE TITLE
Cam-CAN subjects show flipped images in MNI space

### ISSUE THREAD

**Issue by richford** [yeatmanlab/pyAFQ#402]
Also using #384, the b0 image is flipped when transformed to MNI space. Compare [sub-CC120347_space-T1w_desc-preproc_dwi_b0.nii.gz](https://cam-can-mri.s3-us-west-2.amazonaws.com/derivatives/afq/sub-CC120347/sub-CC120347_space-T1w_desc-preproc_dwi_b0.nii.gz) with 
[sub-CC120347_space-T1w_desc-preproc_dwi_b0_in_MNI.nii.gz](https://cam-can-mri.s3-us-west-2.amazonaws.com/derivatives/afq/sub-CC120347/sub-CC120347_space-T1w_desc-preproc_dwi_b0_in_MNI.nii.gz)

Or see these screenshots if you can't download those files. The b0 image is on the left and the b0_in_MNI image is on the right:
<img width="1059" alt="Screen Shot 2020-09-03 at 4 50 11 PM" src="https://user-images.githubusercontent.com/7978135/92184321-afce4700-ee05-11ea-995c-25d997ed85fb.png">

Rotating the b0_in_MNI image around the z-axis by 180 degrees seems to bring it into agreement with the b0 image. i.e. applying an `np.diag([-1, -1, 1, 1])` affine.

FYI, the Cam-CAN input data is LPS orientation. This may be related to #401.

**Comment by arokem** [comment]
I agree that this is puzzling. What about the `*_template_xform.nii.gz` file for this subject? Is it also flipped? The reason I ask is that, unless I am missing something, we don't actually use this `b0_in_MNI` file for anything during the analysis, and it is produced just as a sanity check. The important thing is whether the waypoint ROIs end up in the right place in the subject native space. One indication would be if the `_template_xform` file looks reasonable, because this is the transformation that is also applied to the waypoint ROIs.

**Comment by arokem** [comment]
This might also be related to #397. I am particularly worried about this message: 

```
/usr/local/lib/python3.7/site-packages/AFQ/utils/volume.py:31: UserWarning: Input image is entirely zero, no valid convex hull. Returning empty image
  return convex_hull_image(hole_filled)
```

That seems to suggest that one of the waypoint ROIs came back empty from the registration, which may be the result of a wonky registration.

**Comment by richford** [comment]
The `_template_xform` image is not flipped (`_template_xform` on the left, `b0` on the right):
<img width="875" alt="Screen Shot 2020-09-03 at 9 06 13 PM" src="https://user-images.githubusercontent.com/7978135/92198748-12393e80-ee2a-11ea-844f-6843144f1551.png">

**Comment by arokem** [comment]
This registration is not terrible, as you can see the edges of the brain
roughly aligning. But far from perfect - you can see that the ventricles
are mismatched at the level shown in this slice. I wonder if another
registration strategy would work better for this data. Could you try
registering the individual b0 image to MNI T2 instead?

Also, would you mind posting the anisotropic power map image from this
slice here? The registration currently relies on a good apm and I wonder if
something went wrong in producing that image.

**Comment by richford** [comment]
The anisotropic power map lives [here](https://s3.console.aws.amazon.com/s3/object/cam-can-mri/derivatives/afq/sub-CC120347/sub-CC120347_space-T1w_desc-preproc_dwi_anisotropic_power_map.nii.gz?region=us-west-2&tab=overview) and here is a screenshot:
<img width="530" alt="Screen Shot 2020-09-04 at 1 33 15 PM" src="https://user-images.githubusercontent.com/7978135/92282822-49076700-eeb3-11ea-8bb6-bfce6e2f79b6.png">

**Comment by arokem** [comment]
Is that the APM for the same slice? Looks misaligned with the b0 (and nicely registered with the T1).

**Comment by arokem** [comment]
This might indicate that the subject moved sometime during DWI acquisition from where the b0 was acquired to where the APM is (calculated from the DWI).

**Comment by richford** [comment]
I believe so. I am grabbing them all from https://s3.console.aws.amazon.com/s3/buckets/cam-can-mri/derivatives/afq/sub-CC120347/?region=us-west-2&tab=overview and it's the default slice that loads in mango. All share the same (x, y, z) except for the `in_MNI` image.

Movement doesn't seem too, too bad in the dwi images: https://s3.console.aws.amazon.com/s3/object/cam-can-mri/derivatives/qsiprep/sub-CC120347/dwi/sub-CC120347_space-T1w_desc-preproc_dwi.nii.gz?region=us-west-2&tab=overview

**Comment by arokem** [comment]
OK. I am rather convinced there is no registration issue with this data. Here are images of the registration in MI-Brain, which looks pretty good:

![b0](https://user-images.githubusercontent.com/118582/92293921-f7bf9d80-eedb-11ea-8484-7e98070816f2.png)
![apm](https://user-images.githubusercontent.com/118582/92293923-f8583400-eedb-11ea-8b66-585c88eb0d7a.png)
![template_xform](https://user-images.githubusercontent.com/118582/92293924-f8f0ca80-eedb-11ea-9c5f-d4bdf4a756da.png)

It looks like APM + SyN is a rather solid way of doing registrations, so  I think that we should keep that as our default for now. 

Regarding the flipped b0 in the title of this issue, I believe that #404 is at the root of this problem.

**Comment by arokem** [comment]
Closing in favor of #404
