### ISSUE TITLE
AFQ.data.S3BIDSStudy.download ignores derivatives

### ISSUE THREAD

**Issue by richford** [yeatmanlab/pyAFQ#405]
`AFQ.data.S3BIDSStudy.download()` ignores the `include_derivs` parameter when it is a string. It works when it is a boolean or a list of strings.

**Comment by 36000** [comment]
I added a warning in #409 which might explain why this is happening. Can you show me how you ran into this problem, so I can test your bug on this pull request?

**Comment by richford** [comment]
Sure, you can try it with cam-can using
```
study = afqd.S3BIDSStudy(
        "hbn-qsiprep",
        bucket="cam-can-mri",
        s3_prefix="",
        subjects=1,
        anon=False,
        random_seed=42)
```
And then observe the correct behavior with
```
study.download(
        "good_download_folder",
        include_derivs=["qsiprep"]
)
```
and the incorrect behavior with
```
study.download(
        "bad_download_folder",
        include_derivs="qsiprep"
)
```

**Comment by 36000** [comment]
I tested this locally. For me, "bad_download_folder" and  "good_download_folder" are the same. what version of pyAFQ are you using?

**Comment by richford** [comment]
This was originally happening for me on AWS using [this branch](https://github.com/36000/pyAFQ/tree/avoid_dipy_load_tractogram_bug). However, I'm unable to reproduce locally using the same branch, master, or v0.4.

However, trying this on master led me to open #413 and the resolving #414. I'm surprised that you didn't run into #413, which testing the above locally actually. Anyway, we can close this issue and I'll reopen if it reoccurs (which is unlikely).
