### ISSUE TITLE
Add VOF segmentation

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#430]
There are several different approaches here: 

1. Use Freesurfer-based ROIs. This is the currently-implemented version in Matlab AFQ (@grotheer: where is this function?). 
2. Uses one waypoint ROI and a geometric constraint on the streamlines (have to be approximately horizontal). This is not currently implemented, but @grotheer says she can work on generating the waypoint ROI.
3. There is also an approach implemented here: https://github.com/yeatmanlab/AFQ/blob/master/functions/AFQ_Segment_VOF.m, that uses two waypoint ROIs. Is this approach good? This is a question for @jyeatman + @grotheer. This approach has two waypoint ROIs that both have a 'L' prefix and I don't see any R_VOF ROIs. Does that mean that they only segment the left hemisphere? Or are they somehow reflected into the right hemisphere. I don't see that in the code. Maybe they cover both hemispheres?

**Comment by jyeatman** [comment]
Approach 3 should be deprecated. Here is the relevant matlab function https://github.com/yeatmanlab/AFQ/blob/master/vof/AFQ_FindVOF.m

**Comment by arokem** [comment]
@jyeatman : thanks! IIUC, this is the one that implements approach 1?

**Comment by jyeatman** [comment]
yes
