### ISSUE TITLE
Follow-up from #422: example of using existing tractography

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#434]
I think that we need a bit more documentation to follow up on #422, explaining how to use this feature and possibly even a gallery example that shows how it's done.

**Comment by 36000** [comment]
This is done in: https://github.com/yeatmanlab/pyAFQ/blob/fb3c261e74408dc277cbef5a7462ba1c5487b6e0/examples/tutorial_examples/plot_002_bids_layout.py#L1
