### ISSUE TITLE
Switch from optparse to argparse

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#44]
See https://github.com/yeatmanlab/AFQ-Browser/pull/100

**Comment by richford** [comment]
I'm working on this now but I have a question: right now some of the options expect a comma-separated list of input files. With argparse (using the `nargs` option), we may use a space separated list of files, e.g.:

`$ pyAFQ_dki -d dwi_file_1 dwi_file_2 -l bval_file_1 bval_file_2 -c bvec_file_1 bvec_file_2`

This seems cleaner to me. It would also allow us to enforce the requirement that the number of dwi files is the same as the number of bval files and bvec files. We could catch that early on dring argument parsing rather than deeper in the call stack. But I don't know if this change would break compatibility with other tools in the AFQ pipeline. And if it does, is that a big deal?

**Comment by arokem** [comment]
@libbyhuber, @jyeatman: would this break something that you are doing? I
think that at the worst you would have to replace commas with spaces in
some of the code that you wrote to use this, but let us know if this is
disruptive.

I am otherwise +1 for this change

**Comment by jyeatman** [comment]
That seems like a sensible change. This is where the simple changes would
need to be made in AFQ and it looks like we even have a test function too!
https://github.com/yeatmanlab/AFQ/tree/master/utilities/pyAFQ

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by richford** [comment]
Just to be clear, I think I can reproduce the old behavior with argparse. So the switch isn't mandatory. But space separation with `nargs` seems to be how people are handling lists of input these days so I wanted to take the opportunity to update if it isn't too disruptive. But if it is, there's absolutely no problem with just recreating the old behavior.

**Comment by arokem** [comment]
I think this would be an improvement. The comma-separation thing was a
hack.

It seems that it would entail changing three lines of code in the Matlab
function Jason pointed out, so I really don't think it's too disruptive.

**Comment by jyeatman** [comment]
Go for updating it

We will adjust

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by richford** [comment]
One more suggestion here. We could have just two command line programs: `pyAFQ_fit` and `pyAFQ_predict`. They would both accept a required argument that would be limited to two choices, either `dki` or `dti` and depending on the choice, the command line program would call the appropriate python function. This would cut down on redundant code. But again, it would probably break compatibility.

@arokem and @jyeatman, your thoughts?

**Comment by richford** [comment]
These changes are ready to go. So @arokem and @jyeatman if you're cool with the above mentioned change, I'll go ahead and submit a PR. If not, that's fine too. I'd just roll back my branch a couple of commits and then submit the PR. Let me know either way.

**Comment by arokem** [comment]
Thank you! Please submit PR. We can take the discussion about the API over there. I am still mulling over what would make more sense. I think there are ways to keep current API (maybe clearer?) while reducing duplication (a "cli.py" module?).

**Comment by arokem** [comment]
Done in #94
