### ISSUE TITLE
Do a better job telling warning people when we are making files outside of the working directory

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#449]
This includes .dipy and AFQ_data

**Comment by bloomdt-uw** [comment]
and `.cache/templateflow`

**Comment by bloomdt-uw** [comment]
Ran `dtruss` on `examples/plot_afq_api.py` and can confirm that `~/.cache`, `~/.dipy`, and `~/AFQ_data` were the main _user folders_ outside of the working directory.

(Others include system files and libraries required to run pyAFQ; e.g., `/var`, `/usr/share/`, `/usr/bin/`, `/System/Library`, `/Library`, ...)
