### ISSUE TITLE
Use a dataset that requires a larger prealign than the stanford hardi

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#480]
We use the stanford hardi dataset in almost all of our tests. It is relatively easy to register. In particular, the affine pre-alignment is usually very close to the identity. We should have tests on some datasets that are harder to register.

**Comment by arokem** [comment]
Is this something you were seeing with IXI? It would be possible to upload a couple of preprocessed IXI subjects to figshare, and create a new fetcher to get these data down. In general, it's the kind of thing you would hope the preprocessing would do for you, but it's not always possible.

**Comment by 36000** [comment]
This is the same as #616
