### ISSUE TITLE
sphinx build make clean should clean up after any sphinx-gallery examples files and folders:

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#485]
sphinx build make clean should clean up after any sphinx-gallery examples files and folders:

- multiple files are placed directly into the `examples` folder (this are ignored by git)
- application data folders including `.dipy` and `AFQ_data` (these are not part of source)

Depending on what files are present this may impact local builds

_Originally posted by @bloomdt-uw in https://github.com/yeatmanlab/pyAFQ/pull/476#r494818482_

**Comment by bloomdt-uw** [comment]
- `make clean` runs `sphinx-build -M clean "source" "build"` which only removes files in the `build` directory.
- sphinx-gallery [Cleaning the Gallery Files](https://sphinx-gallery.github.io/stable/advanced.html#cleaning-the-gallery-files) recommends adding `clean` target to `Makefile` to also remove the `auto-examples`:

> `clean:`
> &nbsp;&nbsp;&nbsp;`rm -rf $(BUILDDIR)/*`
> &nbsp;&nbsp;&nbsp;`rm -rf auto_examples/`

- Other are files created during the build process. as shown by running `make html; git -n -dfx`:
> `Would remove build/`
> `Would remove source/auto_examples/`
> `Would remove source/sphinxext/__pycache__/`
> `Would remove source/usage.rst`

I propose leaving `clean` as it is and introducing a few additional Phony Targets, and keeping with [standard make targets](https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html#Standard-Targets):
- `distclean` - leaves only the files that were in the distribution. deletes files created by `sphinx-build` within source.
- `realclean` - delete more files than `distclean`. this would also remove the data files.
