### ISSUE TITLE
Configure sphinx to build only some examples on a particular run

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#486]
another enhancement regarding local sphinx-build would be to allow single example as target (since some of the example execution times are long)

To build only one file I locally updated `conf.py` by adding `filename_pattern`

```
sphinx_gallery_conf = {
     # path to your examples scripts
     'examples_dirs': '../../examples',
     **'filename_pattern': '/plot_callosal_tract_profile.py',**
     # path where to save gallery generated examples
     'gallery_dirs': 'auto_examples',
     'image_scrapers': image_scrapers,
}
```

_Originally posted by @bloomdt-uw in https://github.com/yeatmanlab/pyAFQ/pull/476#r495106207_

**Comment by bloomdt-uw** [comment]
It is possible to use existing documentation build to specify which examples are made.

From sphinx-gallery configuration documentation [Parsing and executing examples via matching patterns](https://sphinx-gallery.github.io/stable/configuration.html#parsing-and-executing-examples-via-matching-patterns):

> Remember that Sphinx allows overriding conf.py values from the command line, so you can for example build a single example directly via something like:
>
> $ sphinx-build -D sphinx_gallery_conf.filename_pattern=plot_specific_example\.py ...

Inspecting `Makefile` there is an `SPHINXOPTS` environment variable that passes arguments through make to sphinx-build. To build single example, or even subset of the examples in the gallery, specify the appropriate combination of regular expressions for `filename_pattern` and `ignore_pattern`.

For example:
`make html SPHINXOPTS="-D sphinx_gallery_conf.filename_pattern=/plot_callosal_tract_profile\.py"`
