### ISSUE TITLE
BabyAFQ

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#487]
@arokem I believe that you mentioned in passing that this example might be relevant to baby-AFQ wondering if you could elaborate and whether we would want to share with Mareike

_Originally posted by @bloomdt-uw in https://github.com/yeatmanlab/pyAFQ/pull/476#r495108048_

**Comment by arokem** [comment]
Indeed! I think that this shows the way... 

I've already placed all the babyAFQ stuff in a figshare repository available here: https://figshare.com/articles/dataset/ROIs_probabilistic_maps_and_transform_data_for_pediatric_automated_fiber_quantification/13027487

The first thing to do would be to download these files into `~/AFQ_data` or somesuch, following the pattern of https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/data.py#L67-L117 

Then, you'll need to replace our MNI T2 template with the babyAFQ template (it's the file called 'UNCNeo-withCerebellum-for-babyAFQ.nii.gz'), and you'll need to replace the waypoint ROIs with the waypoint ROIs, in a similar fashion to the way we do in #476, and we're done.

Tagging in @grotheer, so she's in the loop as we implement this.

**Comment by grotheer** [comment]
Thank you both! Let me know if I can help in any way
