### ISSUE TITLE
Segmentation alters input data space

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#518]
Moved from #399 : 

@soichih says: We recently noticed that AFQ.segment function will modify the input streamline's space. For example, we feed tg.space set to rasmm and pass it to segment(). After the segmentation runs, the tg.space is now set to VOX. We basically had to reload the whole streamline from the disk to revert it back to the rasmm space. Is this an expected behavior?

@giulia-berto made this PR to correct this

brainlife/app-pyafq-segment#1

**Comment by arokem** [comment]
Thanks for reporting this. Indeed, the segmentations are always done in the subject's native space, so the data has to be moved to the VOX space at the outset. But I think that we could keep track of the original space of the input and then move the input back to that space at the very end.

**Comment by giulia-berto** [comment]
Yes, here [https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/segmentation.py#L551](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/segmentation.py#L551) streamlines are moved to VOX space, but then they are not moved back to the original space. I agree that this is not expected.

**Comment by arokem** [comment]
Thanks for reporting. I am working to fix this over on #520. The fix stores the original space as an object attribute and then calls `self.tg.to_space(self._tg_orig_space)` at the end of the `segment` method. Does that cover your use-case?

**Comment by giulia-berto** [comment]
Yes, I think that's what we need, thanks.
