### ISSUE TITLE
Make bundle  input more flexible

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#519]
https://github.com/yeatmanlab/pyAFQ/blob/b60a25b860249b3dc38f11eba8f95012ee6d9bc0/AFQ/api.py#L180

Maybe we can change this to `bundles` instead of `bundle_names`. Then, users can provide a `bundle_dict` input (a dictionary) or a list (in which case the current behavior is retained).

**Comment by 36000** [comment]
I think that ROI and bundle_dict should be classes. Then the user wouldn't have to manage complicated dictionaries, they could look at the docstrings for these classes to see how to instantiate them.

**Comment by arokem** [comment]
Good point. A BundleSpec object for each bundle perhaps and then a collection of these specs as inputs here

**Comment by arokem** [comment]
Will also help us deal with some of the brittleness we currently have wrt order of ROIs endpoints and so forth

**Comment by 36000** [comment]
Other idea in #338 : use a path

**Comment by 36000** [comment]
It really comes down to what is least intrusive to existing workflows and what is least complicated for the end user to provide as input. We should see what Sandra thinks after she uses our bundle_dict interface.

**Comment by 36000** [comment]
This was solved with bundle_info at some point.
