### ISSUE TITLE
Color by volume has a bad color range when using FA on infants.

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#547]
This is because many of the bundles have extremely low FA in infants. This range should be modifiable by the user.

**Comment by jyeatman** [comment]
modifiable by the user is good

also you might have the default be to set the range based on the 5th and 95th percentiles of the data. Or something like that to encapsulate the data range

**Comment by 36000** [comment]
I think that 5th and 95th percentiles of the data is smart. The current range is from 0 to the max of the data. My guess is that the baby AFQ data has a few voxels throwing off this default range.
