### ISSUE TITLE
Add ability to increase distance criteria in ROI intersection

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#548]
https://afq-browser.slack.com/archives/C01CJL85NLS/p1602716531025700

https://github.com/yeatmanlab/pyAFQ/blob/c826d64c29cf0c6f701023e752ee53600358dfb7/AFQ/segmentation.py#L510

https://afq-browser.slack.com/archives/C01CJL85NLS/p1602733820032200
This used to be a kwarg to segmentation, but was then hard-coded. We should change it back to a kwarg

**Comment by bloomdt-uw** [comment]
Alternatively dilate the ROIs using [scikit-image](https://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.binary_dilation)

https://afq-browser.slack.com/archives/C01CJL85NLS/p1602737872033300

**Comment by 36000** [comment]
This was done at some point, and made individual by #625
