### ISSUE TITLE
Add Recommended Usage for Converting from MATLAB AFQ to pyAFQ

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#549]
This could include:

- usage of [pyAFQ-scripts](https://github.com/36000/pyAFQ-scripts)

- recommended processing:

> Do your preprocessing and also reconstruction with another software, and now you’d like to feed it into pyAFQ.

**Comment by arokem** [comment]
I think there are two issues here:

1. I think that @grotheer and @36000 had written some conversion scripts to feed Matlab data into visualization. That would potentially be useful to integrate and document. 
2. There is the more general issue of providing outputs of other analysis pipelines as inputs (e.g., tractography from qsiprep). That is currently supported, and documented in the docstring, but we might want to add some narrative documentation on that in the 'usage' section.

**Comment by bloomdt-uw** [comment]
Two-step pipeline: using qsiprep/mrtrix for tractography followed by segmentation in pyAFQ

Can use `custom_tractography_bids_filters`, which expects BIDS filters.

For example with the outputs of the qsiprep pipeline in the derivatives folder, you can pass in something like:
`custom_tractography_bids_filters = {'scope': 'qsiprep', 'suffix': 'tractography'} `
