### ISSUE TITLE
Use `pip install dask[complete]` to eliminate dependency issues

### ISSUE THREAD

**Issue by richford** [yeatmanlab/pyAFQ#55]
# Issue

I think we're missing some dependencies. When I try to install pyAFQ in a Docker container, `import AFQ` fails because it lacks the `pandas` and `toolz` dependencies. Here's a minimal Dockerfile that recreates the problem.

```
FROM python:3

# Install git so that we can get pyAFQ from its github repo
RUN apt-get update
RUN apt-get install -y git

# Install pyAFQ dependencies
RUN pip install dask
RUN pip install dipy
RUN pip install nibabel
RUN pip install boto3
RUN pip install cloudpickle

# Install pyAFQ from its github repo
RUN pip install git+git://github.com/yeatmanlab/pyAFQ.git@master#egg=pyAFQ
```

If you create an image from this docker file using `docker build -t pyafq .` and then run using `docker run -it pyafq python`, you can replicate the issue by attempting `import AFQ`.

# Solution

One solution is to use `pip install dask[complete]` to pick up pandas and toolz. I recommend we change the requirements from `dask` to `dask[complete]`.

I'm happy to submit a PR for this if you agree.

**Comment by richford** [comment]
Ahh, I see now that this is not an issue with `requirements.txt` but only with `README.md`.

**Comment by arokem** [comment]
Yup - we should get that line out of the README!

I have recently discovered that one way to go is to install software using:

    pip -r requirements.txt
    pip install -e .

or as you do here for the second line directly from git.

**Comment by arokem** [comment]
I believe this is no longer relevant.
