### ISSUE TITLE
This could be optimized by preallocating instead of using `append`

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#56]
https://github.com/yeatmanlab/pyAFQ/blob/daa842b77b4bfd92785dfb3db988444f42b67bfb/AFQ/utils/models.py#L48-L50

**Comment by richford** [comment]
How about something like
```
bvals_array = [np.loadtxt(bval_file) for bval_file in bval_files]
bvals = np.concatenate(bvals_array)
```
and so on for `data` and `bvecs`.

Also, switching to `pandas.read_csv` might save a lot of time. I've heard anecdotally that it can be a lot faster than `numpy.loadtxt`.

I'm happy to take this on but it'll have to wait until I'm at a good stopping point with cloudknot stuff.

**Comment by arokem** [comment]
I believe @aarya22 is on it!

**Comment by richford** [comment]
@arokem, is this worth doing still?

**Comment by arokem** [comment]
I think it's probably a small win (that's almost certainly not the performance bottleneck), but there's no harm in doing this.
