### ISSUE TITLE
Should warn users if encounter uncompressed dwi files in BIDS layout

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#561]
Per #151 pyAFQ does not process uncompressed dwi files. However, it is quite common for preprocessing applications to store raw nii files. To facilitate should notify user what actions to take:

```
# check for uncompressed nii files.
nii = bids_layout.get(subject=subject, session=session,
    extension='nii',
    return_type='filename',
    scope=dmriprep,
    **bids_filters)

if len(nii):
    raise ValueError(
        "Unable to process raw dwi files. "
        "Please compress " + nii
    )
```

**Comment by arokem** [comment]
This is not generally an issue. This is just an issue for files that are read from S3 using `s3fs_nifti_read`. 

I think that the solution should be to improve that function for the use-cases where S3 is being used. At any rate, I don't think that we need this kind of general warning.
