### ISSUE TITLE
Multi-shell multi-tissue (MSMT) tractography is slow

### ISSUE THREAD

**Issue by bloomdt-uw** [yeatmanlab/pyAFQ#563]
This is something observed by @arokem, and has reported current implementation may take several hours to run with pyAFQ. I believe that Mareike has reported that she is able use AFQ to do MSMT in less than an hour. 

As a work-around this is a motivating use two-step processing pipeline for MSMT, where load tractography and only segment using pyAFQ.

**Comment by bloomdt-uw** [comment]
Need an example to demonstrate this behavior.

**Comment by arokem** [comment]
I think that it's worth investigating, but my current belief is that this issue will be very hard to address, without somehow replacing the DIPY dependency on cvxpy. I think it's out of scope for this project (and probably also for DIPY) to solve that right now.
