### ISSUE TITLE
Speed up segmentation by using image interpolation rather than distance criteria

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#575]
I the case where the desired distance criteria is the voxel size, would the ROI segmentation be faster by:
1) Treating the ROI as an image with zeros and ones
2) Interpolating the image values for each streamline (similar to the probability map) with nearest neighbor.
3) Retaining all fibers with any non-zero values in the bundle

@arokem @36000 this might be worth testing out to see if it is a substantial speed up. Keeping the distance calculation as an option is good because there are many cases where people might want to adjust the distance. But it might even be possible to adjust the distance by doing an operation to the image (eg dilation). Since nearest neighbor interpolation is so fast this might be a large speedup. To save memory there should be some way to do it without having to allocate a separate array for fiber probabilities.

**Comment by 36000** [comment]
This is superseded by #1137 which is a very similar idea but without any of the downsides
