### ISSUE TITLE
Consider relaxing numpy version requirements

### ISSUE THREAD

**Issue by richford** [yeatmanlab/pyAFQ#578]
Could we consider changing [the numpy requirement](https://github.com/yeatmanlab/pyAFQ/blob/7d377fd75de34c4a7ae148aed97179081190cfcb/setup.cfg#L33) from `numpy==1.17.5` to `numpy>=1.17.5`. I'm asking because `qsiprep>=0.12.1` will have `numpy==1.18.5`. For various CI reasons it is complicated for them to use 1.17.5.

For interoperability on the HBN project, it would be nice to either change the pyAFQ requirement to `1.18.5` or to `>=1.17.5`.

@arokem, your thought?

**Comment by arokem** [comment]
Closed through #579
