### ISSUE TITLE
Deprecate CLIs

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#586]
For historical reasons, we have several CLIs for fitting and predicting different models. I believe that we are not really using that and there are alternatives in DIPY, so I think that we should deprecate these. WDYT @jyeatman? Is anyone in your group using these CLIs?

**Comment by jyeatman** [comment]
I don't think we need to support that into the future. They are in use for old studies. But those old studies would be pegged to a previous release
