### ISSUE TITLE
pyAFQ hangs on this line with large segmentation files

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#602]
https://github.com/yeatmanlab/pyAFQ/blob/87a85f71affb242c10cec73e4042ddaab17c1164/AFQ/api.py#L1397

**Comment by arokem** [comment]
What we need to do here is read the entire file only once, and when we are done doing that, we should store a class attribute called `total_n_streamlines` or some-such, which will be used upon writing this table. That way, we can avoid reading large files more than once.
