### ISSUE TITLE
empty affines

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#609]
the affines in the outputs should match the inputs. Ideally the affines should be compatible across the most software packages possible. We have a scenario where sometimes the sto is blank and sometimes the qto is blank in the output images. I think we should write both affines. At the very least we should have it match the input data

**Comment by arokem** [comment]
OK - I think that I can reproduce something like this on my end: 

```
In [12]: input = nib.load('derivatives/qsiprep/sub-NDARZZ810LVF/ses-HBNsiteCBIC/dwi/sub-NDARZZ810LVF_ses-HBNsiteCBIC_acq-64dir_space-T1w_desc-preproc_dwi
    ...: .nii.gz')

In [13]: output = nib.load('derivatives/afq/sub-NDARZZ810LVF/ses-HBNsiteCBIC/sub-NDARZZ810LVF_ses-HBNsiteCBIC_acq-64dir_space-T1w_desc-preproc_dwi_model-D
    ...: KI_FA.nii.gz')

In [14]: input.get_sform()
Out[14]: 
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [15]: input.get_qform()
Out[15]: 
array([[ -1.79999995,   0.        ,   0.        ,  95.30000305],
       [  0.        ,  -1.79999995,   0.        , 102.69999695],
       [  0.        ,   0.        ,   1.79999995, -85.19999695],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [16]: output.get_sform()
Out[16]: 
array([[ -1.79999995,   0.        ,   0.        ,  95.30000305],
       [  0.        ,  -1.79999995,   0.        , 102.69999695],
       [  0.        ,   0.        ,   1.79999995, -85.19999695],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [17]: output.get_qform()
Out[17]: 
array([[ -1.79999995,   0.        ,   0.        ,  95.30000305],
       [  0.        ,  -1.79999995,   0.        , 102.69999695],
       [  0.        ,   0.        ,   1.79999995, -85.19999695],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

The question is then: what would be the right outcome here? Do we want to duplicate that weird all-zeros matrix into the output?

**Comment by arokem** [comment]
I will say: this doesn't exactly replicate the findings in Matlab (as I understand them), where: 

<img width="403" alt="Screen Shot 2020-12-02 at 11 02 50 AM" src="https://user-images.githubusercontent.com/118582/100933008-8f179b00-34a1-11eb-859c-c869415ac3f5.png">
<img width="402" alt="Screen Shot 2020-12-02 at 10 54 03 AM" src="https://user-images.githubusercontent.com/118582/100933014-90e15e80-34a1-11eb-8946-b892d7c6e914.png">

**Comment by arokem** [comment]
It's also not exactly the same data either, so there might be more to it.

**Comment by 36000** [comment]
It looks like an empty affine was not the problem in this case.

**Comment by arokem** [comment]
Yeah - looks like this is a qsiprep (and maybe also Matlab) issue.
