### ISSUE TITLE
Error pulling data when running plot_afq_api.py in a singularity container

### ISSUE THREAD

**Issue by gkiar** [yeatmanlab/pyAFQ#633]
I was trying to run the `plot_afq_api.py` example on a shared system via singularity, and had the following issue.

To avoid duplicating the download of everything from my local run, and preparing for nodes without internet access, I copied over my previously crawl of the online sources. I put them in a findable location by dipy/pyafq (as evidenced by the first few lines), but I am still getting an error as though the tool is trying to download some of the files (and not finding a valid certificate to do so), apparently prior to checking for their existence and saving itself the hassle.

I again confirmed that all the files were copied by doing a `diff` between the local dipy and pyafq directories and those on the shared system, and indeed they match exactly. Any ideas?

I think that regardless of the specific certificate issue in this case, this is a problem as any time you're running a job on a cluster you will not have access to internet so can't download the template for your jobs; or even if you did, you'd be doing so dozens of times in parallel on the same system. It would be great if we checked for the existence of a template/stored it in the same structure alongside the other templates rather than re-downloading it each time.

```python
INFO:AFQ.data:fetching Stanford HARDI data
INFO:dipy.data.fetcher:Dataset is already in place. If you want to fetch it again please first remove the folder /home/gkiar/.dipy/stanford_hardi
INFO:AFQ.data:Dataset is already in place. If you want to fetch it again please first remove the folder /home/gkiar/AFQ_data/stanford_hardi/derivatives
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz
Traceback (most recent call last):
  File "examples/plot_afq_api.py", line 98, in <module>
    myafq = api.AFQ(bids_path=op.join(afd.afq_home,
  File "/usr/local/lib/python3.8/site-packages/AFQ/api.py", line 510, in __init__
    self.reg_template_img, _ = self._reg_img(self.reg_template, False)
  File "/usr/local/lib/python3.8/site-packages/AFQ/api.py", line 990, in _reg_img
    img = afd.read_mni_template(
  File "/usr/local/lib/python3.8/site-packages/AFQ/data.py", line 2349, in read_mni_template
    template_img = nib.load(str(tflow.get('MNI152NLin2009cAsym',
  File "/usr/local/lib/python3.8/site-packages/templateflow/api.py", line 68, in get
    _s3_get(filepath)
  File "/usr/local/lib/python3.8/site-packages/templateflow/api.py", line 208, in _s3_get
    r = requests.get(url, stream=True)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by arokem** [comment]
Hmm. Looks like on [this](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/data.py#L2356) line `tflow.get` doesn't check whether the file is already in place? Seems like it should. Maybe we should report this upstream to templateflow.

**Comment by gkiar** [comment]
At first that is what I thought, but then I wasn't sure if the file actually gets stored to disk, since in the call on the line you linked I couldn't find a destination path. In that case, the burden would fall on us to save it. However, I haven't used templateflow so don't know what the save behaviour is given a call like that one.

**Comment by arokem** [comment]
No, looks like it definitely does avoid downloading on repeat calls. Does the path somehow change from time to time? 

What happens if you repeat this call?

```
from templateflow import api as tflow
tflow.get('MNI152NLin2009cAsym',
                                           desc=None,
                                           resolution=2,
                                           suffix="T2w",
                                           extension='nii.gz')
```

**Comment by gkiar** [comment]
Not on my local execution, though admittedly I can't find a file by that exact name in the `.dipy` or `AFQ_Data` directories. Where does it get stored locally for you?

**Comment by arokem** [comment]
I get `PosixPath('/Users/arokem/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz')`

**Comment by gkiar** [comment]
Ok so looking in my `~/.cache/templateflow` directory I was able to find and copy all of the files used by the execution and avoid redownloading. Thanks for help debugging!
