### ISSUE TITLE
AFQ browser integration

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#702]
Proposed changes to pyAFQ:

- [x] Make sure that pyAFQ's output tract profiles do not have the index column that pandas attaches by default
- [x] Update pyAFQ to have a function to generate an afq browser instance
- [x] generate streamlines.json from just first subject (How to handle no streamlines found?)

Proposed changes to the AFQ-Browser assemble API:

- [x] source can be existing nodes.csv file (this makes AFQ-Browser more easily compatible with other pipelines) (document this as pyAFQ first)
- [x] Add another streamlines.json path argument (note to the user that needs to be in MNI)
- [x] Extra: additional input that would be a dictionary, whose keys are subject/session and values are paths to plotly visualizations, these links show up somewhere in AFQ-Browser

**Comment by 36000** [comment]
Make sure that pyAFQ's output tract profiles do not have the index column that pandas attaches by default

**Comment by bloomdt-uw** [comment]
There is an existing Helper function to create a minimal metadata file:

https://github.com/bloomdt-uw/AFQ-Browser/blob/fcb5222417c020afebaebab4307424b22f154c1e/afqbrowser/browser.py#L75-L79

**Comment by 36000** [comment]
Useful AFQ-browser links:
https://yeatmanlab.github.io/AFQ-Browser/dataformat.html
https://github.com/yeatmanlab/AFQ-Browser/blob/master/bin/afqbrowser-assemble

Example working pyAFQ-browser (took assembled instance, replaced nodes.csv and subjects.csv):
https://github.com/yeatmanlab/UW_PREK_pyAFQ_pre_browser

**Comment by 36000** [comment]
Proposed changes to the AFQ-Browser assemble API:

- [ ] source can be existing nodes.csv file (this makes AFQ-Browser more easily compatible with other pipelines)
- [ ] streamlines.json file should be an optional path just like metadata
- [ ] streamlines.json input could also be a dictionary, whose keys are subject/session and values are paths to plotly visualizations
- [ ] User tells the program if they are using matlab vs tracula vs nodes.csv (at the very least, throw an error earlier if input does not match one of these)

**Comment by bloomdt-uw** [comment]
https://github.com/yeatmanlab/AFQ-Browser/pull/287

Adds support for `nodes.csv`, optional metadata, optional streamline file, and validates inputs.

To use can either call the `afqb.assemble` API or use `bin/afqbrowser-assemble` CLI

If no metadata is provided, then will generate a `subjects.csv` with `subjectID` from `nodes.csv`
If no streamlines file is provided, then will use default anatomy.

**Comment by arokem** [comment]
I believe that everything except the integration of plotly visualizations into afqb is addressed through the combination of #703 and https://github.com/yeatmanlab/AFQ-Browser/pull/287 (which is now in the released version 0.3 of AFQ-Browser) 🎉

**Comment by arokem** [comment]
Closed through #670. The extra task mentioned above is part of NIRV now.
