### ISSUE TITLE
pyAFQ with brain lesions

### ISSUE THREAD

**Issue by dubergonzoni** [yeatmanlab/pyAFQ#715]
Dear pyAFQ team,

Please, there's anny recomendation or citation showing the possibility to use pyAFQ with Stroke Brain Lesions?

I ran the pyAFQ code integrated with AFQ-Browser and, obviously, the tractography is not showing some tracts near the lesion. But I was wondering if it's possible to adjust the pyAFQ parameters to get a better tractography with stroke patients? Maybe reduce the fa threshold?
Sorry for this beginner's tractography question.

Thank you!

**Comment by arokem** [comment]
Thanks for asking! I think that this is better suited as a "discussion", rather than an "issue", so I moved it over here: https://github.com/yeatmanlab/pyAFQ/discussions/716. I'll close this issue and try to give an answer in the discussion.
