### ISSUE TITLE
New `BundleDict` limits flexibility of bundle specification

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#717]
Sorry that I didn't notice this on review of #691, but I now noticed that the new implementation of the `BundleDict` object limits somewhat the ability of users to specify a set of waypoint ROIs that they would like to use to delineate a bundle. For example, in work on #646, I want to write something like: 

```
or_rois = afd.read_or_templates()

bundles = api.BundleDict({
    "L_OR": {
        "ROIs": [or_rois["left_OR_1"],
                 or_rois["left_OR_2"],
                 or_rois["left_OP_MNI"],
                 or_rois["left_TP_MNI"],
                 or_rois["left_pos_thal_MNI"]],
        "rules": [True, True, False, False, False],
        "cross_midline": False,
        "uid": 1
        },
    "R_OR": {
        "ROIs": [or_rois["right_OR_1"],
                 or_rois["right_OR_2"],
                 or_rois["right_OP_MNI"],
                 or_rois["right_TP_MNI"],
                 or_rois["right_pos_thal_MNI"]],
        "rules": [True, True, False, False, False],
        "cross_midline": False,
        "uid": 2
        }
    }
)
```

And then pass that as the `bundle_info` input to initialize an `AFQ` object. But that currently is not possible, because it hits [this line](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/api.py#L232) and errors out. That's because the BundleDict object assumes that if you are using the `afq` algo, you will only ever use the templates that get return by [read_templates](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/api.py#L182). But, in general, we want users to be able to build any specification that they'd like. This was previously possible, because it really was just a dict, but is now no longer possible. We need to think how to over-ride this. Maybe if you provide a dict input to `BundleDict`, we set `self.all_gen = True` and avoid running through `gen_all`?

**Comment by 36000** [comment]
"Maybe if you provide a dict input to BundleDict, we set self.all_gen = True and avoid running through gen_all?"
Yes, this is exactly right. Good catch! I have a fix in this PR: #718 . I also added a test. Could you try this fix in your PR, and if it works, maybe you can use the OR templates as another BundleDict test?
