### ISSUE TITLE
Nightly failure with "synthetic" derivatives path

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#722]
Here is the specific error: https://github.com/yeatmanlab/pyAFQ/runs/2941021518?check_suite_focus=true#step:6:455

@36000 : do you understand what this is about?

**Comment by 36000** [comment]
We now throw a more specific error, earlier in this case, but I forgot to update the test. So it is just trying to pytest.raise the wrong error. I will update the test. I am glad it threw an error we could see instead of just a memory error (:
