### ISSUE TITLE
Error messages not descriptive enough

### ISSUE THREAD

**Issue by pierre-nedelec** [yeatmanlab/pyAFQ#728]
Hi pyAFQ team! Awesome job with this tool, it's fantastic.

I'm running into issues with some of my data. It looks the same as another input for which the pipeline worked perfectly, and I'm currently going through the error messages but they're a bit cryptic to me.

Error message:
```py
+ path/to/AFQ/pyAFQ/bin/pyAFQ /scratch/34528.1.member.q/ABCD_003/config.toml
INFO:pyAFQ:Your use of pyAFQ is being recorded using Google Analytics. For more information, please refer to the pyAFQ documentation: https://yeatmanlab.github.io/pyAFQ/usage.html#usage-tracking-with-google-analytics. To turn this off, use the `--notrack` flag when using the pyAFQ CLI
Loading AFQ libraries...
Traceback (most recent call last):
  File "path/to/AFQ/pyAFQ/bin/pyAFQ", line 101, in <module>
    afb.parse_config_run_afq(
  File "path/to/AFQ/pyAFQ/AFQ/utils/bin.py", line 262, in parse_config_run_afq
    myafq = api.AFQ(bids_path, **kwargs)
  File "path/to/AFQ/pyAFQ/AFQ/api.py", line 668, in __init__
    bvec_file_list.append(bids_layout.get_bvec(dwi_data_file,
  File "path/to/AFQ/env/lib/python3.8/site-packages/bids/layout/layout.py", line 1010, in get_bvec
    return listify(result)[0]
IndexError: list index out of range
```

My data is organized as per instructions. Do you have a way to display more precise error messages? I tried the flag `-v` but it didn't help. I realize that might be more on the AFQ end than pyAFQ though...

Thanks!
Pierre

**Comment by arokem** [comment]
No - this is definitely the right place to post about this. I wonder whether the recent #691 might provide more useful errors. I assume that you installed it using `pip`? If so, you can run a `pip install -U pyAFQ` to get the version we released earlier today, and that should have that pull request integrated into it. If you still get this cryptic error with the new release, we should try to get further to the bottom of your error. Thanks for reporting!

**Comment by pierre-nedelec** [comment]
There was actually an issue with the naming of some images, it didn't fully followed the standards that you indicated. I haven't tried the latest version yet, so I can't confirm yet if the error messages are more helpful. Will let you know if I get around to checking this!

**Comment by arokem** [comment]
I'll close this one for now, and we can follow up on another issue as needed.
