### ISSUE TITLE
DKI Bundles Rendering

### ISSUE THREAD

**Issue by bjbalken-zz** [yeatmanlab/pyAFQ#730]
We are running tractography on DKI data and looking to get tract profiles and visualize the segmented bundles. We have been running into an issue with rendering, though. We are running this in the docker container. We tried fury but the docker image doesn't seem to support that by default. When using plotly backend to write html interactive figures, the browser times out after several minutes with nothing displayed. Do we need to be downsampling the tracts? Any other recommendations?

See script below.

Thanks in advance.

```
from AFQ import api
from AFQ.models.dki import fit_dki
from AFQ.tractography import track
from AFQ.segmentation import Segmentation
from dipy.io.streamline import save_trk
import nibabel as nb
from glob import glob
from dipy.stats.analysis import afq_profile, gaussian_weights
import numpy as np
import nibabel as nib
from AFQ.viz.plotly_backend import visualize_bundles, visualize_volume



# data_files = glob('/root/AFQ_data/DKI/derivatives/BIDS/sub-*/ses-*/dwi/*.nii.gz')
# bval_files = glob('/root/AFQ_data/DKI/derivatives/BIDS/sub-*/ses-*/dwi/*.bvec')
# bvec_files = glob('/root/AFQ_data/DKI/derivatives/BIDS/sub-*/ses-*/dwi/*.bvec')


brainmask = '/root/AFQ_data/DKI/derivatives/BIDS/derivatives/afq/sub-7729/ses-Plasticity/sub-7729_ses-Plasticity_dwi_brain_mask.nii.gz'
brainmask = nb.load(brainmask).get_fdata()

data_files = '/root/AFQ_data/DKI/derivatives/BIDS/sub-7729/ses-Plasticity/dwi/sub-7729_ses-Plasticity_dwi.nii.gz'
bvals = '/root/AFQ_data/DKI/derivatives/BIDS/sub-7729/ses-Plasticity/dwi/sub-7729_ses-Plasticity_dwi.bval'
bvecs = '/root/AFQ_data/DKI/derivatives/BIDS/sub-7729/ses-Plasticity/dwi/sub-7729_ses-Plasticity_dwi.bvec'

DKI = fit_dki(data_files, bvals, bvecs, mask=brainmask, b0_threshold=50)

DKI_tracts = track(DKI['params'], directions='det', random_seeds=False, rng_seed=None)

#fname = '/root/AFQ_data/DKI/derivatives/BIDS/derivatives/sub-7729/ses-Plasticity/dwi/sub-7729_ses-Plasticity_DKI.trk'
#save_trk(DKI_tracts, fname)


bundle_names = ["AC", "AF", "AR", "AST", "C", "CB", "CC_ForcepsMajor",
                   "CC_ForcepsMinor", "CC", "CCMid", "CNII", "CNIII",
                   "CNIV", "CNV", "CNVII", "CNVIII", "CS", "CST", "CT",
                   "CTT", "DLF", "EMC", "F_L_R", "FPT", "ICP", "IFOF", "ILF",
                   "LL", "MCP", "MdLF", "ML", "MLF", "OPT", "OR", "PC", "PPT",
                   "RST", "SCP", "SLF", "STT", "TPT", "UF", "V", "VOF"]


BUNDLES = api.BundleDict(bundle_names, seg_algo='reco80')


myseg = Segmentation(nb_points=False, nb_streamlines=False, seg_algo='reco80', reg_algo="syn", clip_edges=False, parallel_segmentation={'n_jobs': -1, 'engine': 'joblib', 'backend': 'loky'}, progressive=True, greater_than=50, rm_small_clusters=50, model_clust_thr=1.25, reduction_thr=25, refine=False, pruning_thr=12, b0_threshold=50, prob_threshold=0, dist_to_waypoint=None, rng=None, return_idx=False, presegment_bundle_dict=None, presegment_kawrgs={}, filter_by_endpoints=True, endpoint_info=None, dist_to_atlas=4, save_intermediates=None)
seg_result = myseg.segment(BUNDLES, DKI_tracts, fdata=data_files, fbval=bvals, fbvec=bvecs)


measures = ['FA', 'MD', 'AD', 'RD', 'MK', 'AK', 'RK']
tracts = list(seg_result.keys())

PpID = DKI['params'][DKI['params'].find('sub-')+4:DKI['params'].find('sub-')+8]

for measure in measures:
    print(measure)
    img = nib.load(DKI[measure])
    data = img.get_fdata()
    for tract in tracts:
        print(tract)
        tractogram=seg_result[tract]
        if len(tractogram.streamlines)==0:
            continue
        weights = gaussian_weights(tractogram.streamlines)
        profile = afq_profile(data, tractogram.streamlines,
                              np.eye(4), weights=weights)
        fname = f'/{PpID}_{tract}_{measure}.csv'
        np.savetxt(fname, profile, delimiter=',', newline='\n')
        

colors = [tuple(np.random.choice(range(256), size=3)) for bundle in range(0, len(seg_result))]


figure = plotly_backend.visualize_bundles(DKI_tracts, n_points=None, bundle_dict=seg_result, colors=colors, cbv_lims=[None, None], flip_axes=[False, False, False], figure=None, interact=True, inline=False)
figure = plotly_backend.visualize_volume(data_files, figure=figure, show_x=True, show_y=True, show_z=True, interact=False, inline=False, opacity=0.3, flip_axes=[False, False, False], slider_definition=20, which_plane=None)




```

**Comment by arokem** [comment]
I believe that the visualization already downsamples the bundles, but you might still end up with rather large files. How large are they? Are you able to share one of these htmls, so we can inspect it to see what's going on? 

Either way, I think that it would be good to add Fury into the container, so we should do that as well.

**Comment by arokem** [comment]
Also, thanks for reporting!

**Comment by bjbalken** [comment]
The html file is 503 MB. I tried downsampling to 100 (161 MB) and it displays now but seems incorrect. It seems like not all bundles are there and the legend shows more bundles than there are labels. I think my inputs are wrong. Is there a more straightforward way to go from segmentation to visualization?

Thanks,
Brendan

HTML File and the rest of the sandbox I'm working in. (This data is from my brain so I can share it).
https://musc.box.com/s/j844kq3njdxv6z87m6fzg8g1b1njwwpo

**Comment by arokem** [comment]
This definitely looks like a bug. Possibly in going from recobundles to visualizations. 

I can't access the data you shared, but can offer an answer to your last question for now. If you'd like to quickly visualize the data you do also have trk files stored in the afq outputs folder (under the clean_bundles folder), so you can load these into your favorite trk file viewer (I often use [imeka's mibrain](https://imeka.ca/mi-brain/)).

**Comment by arokem** [comment]
I can't see the files you shared in box. Could you possibly share that with my gmail account (arokem-at-gmail-doc-com)?

**Comment by bjbalken** [comment]
Thanks I'll check that tool out! I just tried resharing the box folder. Let me know if you still have trouble accessing it.

**Comment by arokem** [comment]
I couldn't figure out what was going on based on the data you shared. One thought that I have is that you might benefit from calling the underlying functions using the [object oriented API](http://yeatmanlab.github.io/pyAFQ/autoapi/AFQ/api/index.html#AFQ.api.AFQ) rather than processing the data through a script. One reason for that is that it automatically keeps track of the spaces in which different images and tractography results are stored and tries to make sure that things don't go catty wumpus in putting things together.
