### ISSUE TITLE
Cleaning up ATR with exclusion ROIs

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#743]
Long-standing issue that ATR often looks like it includes bits and pieces of other bundles: primarily CST. For example, here in the AFQ-Browser streamlines: 

<img width="759" alt="Screen Shot 2021-09-27 at 2 15 08 PM" src="https://user-images.githubusercontent.com/118582/134986329-77c65c36-0325-4fc9-b79c-2e8fa331ae65.png">

One option for tackling that would be to add exclusion ROIs. For example, the CST inclusion ROIs. Worth an experiment. @jyeatman : have you ever tried something like this?

**Comment by 36000** [comment]
This was fixed with start and end ROIs
