### ISSUE TITLE
[help wanted] Using QSIPrep derivatives

### ISSUE THREAD

**Issue by smeisler** [yeatmanlab/pyAFQ#765]
Hello,

I am trying to use pyAFQ (0.9.0) to reconstruct two tracts using DWI preprocessed with QSIPrep (0.13.0). I am using the following code, adapted from the pyAFQ documentation:

```
from AFQ import api

bids_path=$PATH_TO_BIDS
bundle_info = ["ILF", "CST"]

my_afq = api.AFQ(
    bids_path,
    preproc_pipeline='qsiprep',
    bundle_info=bundle_info,
    custom_tractography_bids_filters={
        "suffix": "preproc_dwi",
        "scope": "qsiprep"
    },
    segmentation_params={'nb_streamlines': 10000})

my_afq.export_all()
```

I get the following error: 

```
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/AFQ/api.py", line 887, in __init__
    bids_layout = BIDSLayout(bids_path, derivatives=True)
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/bids/layout/layout.py", line 162, in __init__
    self.add_derivatives(
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/bids/layout/layout.py", line 470, in add_derivatives
    deriv_paths = validate_derivative_paths(paths, self, **kwargs)
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/bids/layout/validation.py", line 150, in validate_derivative_paths
    raise BIDSDerivativesValidationError(
bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside 'dataset_description.json'. 
Example: {'PipelineDescription': {'Name': 'Example pipeline'}}
```

In my `$BIDS/derivatives/qsiprep ` folder, there is a` dataset_description.json file` automatically generated by QSIPrep that contains the field that is supposedly missing. Is there something I'm missing?

Thanks,
Steven

**Comment by arokem** [comment]
Hi Steven, 

Thanks for posting your issue. I am sorry that this is not working as expected. Let me see if I can help to debug this. Would you mind posting the contents of that `dataset_description.json` file? pybids can be pretty finicky about what this should look like, so I want to make sure.

**Comment by smeisler** [comment]
Hi Ariel,

Contents are below:

```
{
    "Name": "qsiprep output",
    "BIDSVersion": "1.1.1",
    "PipelineDescription": {
        "Name": "qsiprep",
        "Version": "0.14.2",
        "CodeURL": "https://github.com/pennbbl/qsiprep/archive/0.14.2.tar.gz"
    },
    "CodeURL": "https://github.com/pennbbl/qsiprep",
    "HowToAcknowledge": "Please cite our paper (), and include the generated citation boilerplate within the Methods section of the text.",
    "SourceDatasetsURLs": [
        "https://doi.org/10.18112/openneuro.ds003604.v1.0.2"
    ],
    "License": "CC0"
}
```

Thanks,
Steven

**Comment by arokem** [comment]
Hi Steven, 

Does it work if you change the first `"Name"` field value to be just `"qsiprep"`?
```
{
    "Name": "qsiprep",
    "BIDSVersion": "1.1.1",
    "PipelineDescription": {
        "Name": "qsiprep",
        "Version": "0.13.0",
        "CodeURL": "https://github.com/pennbbl/qsiprep/archive/0.13.0.tar.gz"
    },
    "CodeURL": "https://github.com/pennbbl/qsiprep",
    "HowToAcknowledge": "Please cite our paper (), and include the generated citation boilerplate within the Methods section of the text.",
    "SourceDatasetsURLs": [
        "https://doi.org/TODO: eventually a DOI for the dataset"
    ],
    "License": "TODO: choose a license, e.g. PDDL (http://opendatacommons.org/licenses/pddl/)"
}

```

**Comment by smeisler** [comment]
So far it appears to be working!

**Comment by arokem** [comment]
Oh bummer. Let me think about this.

**Comment by richford** [comment]
I believe internally, pyAFQ is using the pybids `BIDSLayout` class' `get` method to query the BIDS dataset. pyAFQ passes the `preproc_pipeline` parameter to the pybids `get` method's `scope` parameter, which in turn queries the `Name` field in the `dataset_description.json` file (not the directory name). So this might be an upstream bug inQSIPrep. Ideally, QSIPrep would create a `dataset_description.json` file with `"Name": "qsiprep"`.

**Comment by arokem** [comment]
Yes, but on further thought, I don't think that `"Name"` of the dataset has to match the `"Name"` of the pipeline. For example, in our BIDS example, the name of the dataset is always the same ("Stanford HARDI"), even while there are several different pipelines involved. So, my intuition was wrong and I believe that qsiprep is doing something odd if it is changing the name of the dataset to "qsiprep output", but maybe that's something that @smeisler did, in which case that should still be fine. 

@smeisler : another thing that I noticed is that the suffix for the tractography file that you are looking for is `"preproc_dwi"`. One thing that we've noticed is that the suffix has to be unique in order for pybids to find the tractography file. For example, by having the name of the file end with `_tractography.trk`, as in our BIDS example.

**Comment by smeisler** [comment]
If I have only run qsiprep for the subject (that is, not qsirecon), can pyafq work with my preprocessed derivatives to run the rest of the tractography pipeline from there? That is why I specified the parameters that I did, as all of QSIPrep's preprocessed derivatives (dwi, gradient info) end with `preproc_dwi.nii.gz/.bval/.bvec/.b`.

**Comment by arokem** [comment]
Got it. Yes! That should work, but then you don't need this argument:

```
 custom_tractography_bids_filters={
        "suffix": "preproc_dwi",
        "scope": "qsiprep"
    }
```

This is only needed if you have a tractography file (i.e., a .trk or some-such) that you would like to pull into processing. I think that for the use-case that you describe, dropping that argument and proceeding should work (and each subject should have only 10,000 streamlines generated, based on your last input argument).

I wonder if we should clarify that in our BIDS example 🤔

**Comment by smeisler** [comment]
I removed the `custom_tractography_bids_filters` argument, and still get the same error. This is with the modified `dataset_description.json` with the `name` field set to `qsiprep` instead of `qsiprep output`.

**Comment by arokem** [comment]
Sorry that this is still not working. Let's step back a bit. What happens if you run the following?

```
import bids
bids_path = $PATH_TO_BIDS
layout =  bids.BIDSLayout(bids_path, derivatives=True)
print(layout.derivatives)
```

**Comment by smeisler** [comment]
Still getting the same error :(

**Comment by arokem** [comment]
I'd say there's something not-quite-BIDSish about that BIDS dataset. If that bids_path is directly the output of qsiprep, it might be a qsiprep bug after all, so we might want to also raise that there as an issue, but let's try to sort this out:

Would you mind pasting in the output of `tree $PATH_TO_BIDS`? 

Hopefully that's not too big to paste here :-)

**Comment by smeisler** [comment]
It is unfortunately a bit too big to paste here (there are a few big folders that shouldn't be there that I've tried to patch up by putting them in a `.bidsignore`). I will try to replicate this on a different and cleaner BIDS dataset.

**Comment by smeisler** [comment]
I got the same error.

**Comment by arokem** [comment]
On a simplified qsiprep derivatives dataset? What does that one look like?

**Comment by smeisler** [comment]
This is using ds003604 (https://openneuro.org/datasets/ds003604/versions/1.0.4), a BIDS-valid openneuro dataset, and a recent QSIPrep run (0.14.2).

**Comment by arokem** [comment]
OK - this seems like a qsiprep bug. Let me post on the qsiprep GitHub repo and see whether we can resolve this together.

**Comment by arokem** [comment]
OK - not exactly a bug. I would say that currently pybids validation can't operate on outputs of qsiprep, because the spec hasn't caught up with the kinds of derivatives that are already routinely being generated in the wild. We're working on it... 

For the time being, I think that we need a way to tell pyAFQ that it is going to ingest a BIDSish set of derivatives, but that it should not try to validate them.  

@36000: How did we deal with these issues in the past? We have successfully ingested derivatives from other pipelines on several occasions, including from qsiprep. How do we avoid validation failure in those cases?

**Comment by 36000** [comment]
Interesting, we have worked with QSIprep in the past so I am not sure what the difference is here. Regardless, in the current master of pyAFQ, there is a parameter `bids_layout_kwargs` which you can use to turn off validation. Note that in current master there is also a slightly different interface, where the `GroupAFQ` class replaces `AFQ`, ie:
```
from AFQ.api.group import GroupAFQ
myafq = GroupAFQ(..., bids_layout_kwargs={"validate": False, "index_metadata": False}, ...)
```
@arokem , I think we can cut a release with these changes. Just checked nightly and all tests are passing.

**Comment by smeisler** [comment]
Hi, just updating to say everything seems to be running on 0.10.0 (after changing AFQ to GroupAFQ)! If I want to run parallel jobs in an sbatch array, with one job per subject, would I use participant AFQ? The API for that isn't clear to me at the moment.

Thanks!
