### ISSUE TITLE
Trouble with pyAFQ CLI

### ISSUE THREAD

**Issue by nmuncy** [yeatmanlab/pyAFQ#767]
This seems related to issue 763.

I have tried running pyAFQ with two different config.toml files (config_emu-AFQ.toml, config_emu-UNC.toml), where I was previously successful with config_emu-AFQ.toml. Installed (version 0.9) via pip in a new conda environment (python=3.8). I have the same error in Mac OSx, Ubuntu 20.04, and RHEL 7. Running via `$ pyAFQ config.toml --notrack |& tee log`.

I will attach the file tree, config files (txt versions for github), and captured stdout/err (log). Additionally, this is resolved via fix.py (txt here), so I'm pretty confident it is not my config.toml file, but the way an (empty) dictionary is passed between modules?

Finally, I would love an entrypoint or some guidance on the docker image, and to be able to convert the image to a singularity for CLI usage.

Big fan of your work!

Config files:
[config_emu-AFQ.txt](https://github.com/yeatmanlab/pyAFQ/files/7499476/config_emu-AFQ.txt)
[config_emu-UNC.txt](https://github.com/yeatmanlab/pyAFQ/files/7499484/config_emu-UNC.txt)

Log files:
[log_emu-AFQ.txt](https://github.com/yeatmanlab/pyAFQ/files/7499498/log_emu-AFQ.txt)
[log_emu-UNC.txt](https://github.com/yeatmanlab/pyAFQ/files/7499499/log_emu-UNC.txt)

Fix files:
[fix.txt](https://github.com/yeatmanlab/pyAFQ/files/7499503/fix.txt)
[log_fix.txt](https://github.com/yeatmanlab/pyAFQ/files/7499504/log_fix.txt)

Tree:
<img width="482" alt="Screen Shot 2021-11-08 at 2 03 48 PM" src="https://user-images.githubusercontent.com/15880361/140803538-882f5e45-d327-4869-a52e-cf0ebf354c22.png">

**Comment by 36000** [comment]
Hello,

Thank you for posting this issue! I am glad you are able to get it working and I agree your config files look good. I will debug this and we can do a quick release.

For the images we generate, they currently do not have an entrypoint, they only have pyAFQ installed in them. You can pull them with:
`docker pull ghcr.io/nrdg/pyafq:latest`
I will add the pyAFQ CLI as an entrypoint in the docker image for next version.

**Comment by nmuncy** [comment]
Thank you for the help, I really appreciate it.
I appear to have replicated the issue with the docker? I'm am very likely doing something completely wrong, so I'll just apologize now.

Docker call:
[run_docker.txt](https://github.com/yeatmanlab/pyAFQ/files/7508384/run_docker.txt)

Docker log:
[log_docker.txt](https://github.com/yeatmanlab/pyAFQ/files/7508387/log_docker.txt)

Tree - with the partial AFQ output:
![Screen Shot 2021-11-09 at 5 30 45 PM](https://user-images.githubusercontent.com/15880361/141016212-f2cf886d-d64a-4036-8d8e-eb616b250a55.png)

**Comment by 36000** [comment]
I think you are doing everything correctly! I found the issue - our default config file populates the seed mask and stop mask parameters incorrectly. We will shortly release a new version with that fix. Until then, I believe you have already found a work around?

**Comment by 36000** [comment]
I didn't mean for this to close - I will post here when the new version it out.

**Comment by 36000** [comment]
The new pyAFQ 0.10 should fix this issue. Thank you for bringing this to our attention!
