### ISSUE TITLE
Tagging docker image not working as hoped for

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#773]
Looks like this is still not working as we hoped for: 

https://github.com/yeatmanlab/pyAFQ/runs/4195733521?check_suite_focus=true

I can't tell what the tag format is there, but I assume it's not "0.9.1". Something for us to do next week, I guess.

**Comment by arokem** [comment]
This might be a good lead: https://stackoverflow.com/a/66403227

**Comment by 36000** [comment]
Fixed in #775 , finally!
