### ISSUE TITLE
Looks like plotly is now required for CI

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#780]
https://github.com/yeatmanlab/pyAFQ/runs/4447320915?check_suite_focus=true#step:7:222

**Comment by 36000** [comment]
Fixed by #785 . Problem here is that matplotlib became required but it was not installed. We do not require matplotlib by default. In fact I am not sure why this was not a problem earlier. Maybe matplotlib was sneaking on the machine somehow?
