### ISSUE TITLE
Experiment with TRX

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#782]
This is a prototype for a new tractography file format implemented in https://github.com/frheault/tractography_file_format. It aims to address some of the issues that we have been facing with trk and such, but is not yet a commonly-used exchange format (e.g., other software for visualization or analysis does not yet support it). As a way of advancing the development and use of the TRX format, it might be interesting for us to experiment with producing TRX outputs _as a non-default setting_

**Comment by 36000** [comment]
It's now our default!
