### ISSUE TITLE
Best way to run subjects in parallel?

### ISSUE THREAD

**Issue by smeisler** [yeatmanlab/pyAFQ#783]
Hi PyAFQ team,

I'm used to submitting a SLURM job array to process individual subjects. When I tried this in PyAFQ by defining a `GroupAFQ` instance and passing the specified job's subject label into the `participant_label` argument, `export_all` ran fine with the exception of the AFQ browser output. Only the first subject had an output, and the other jobs threw errors as they attempted to overwrite the directories the first job made. I could not find an `export_all` analog for `ParticipantAFQ`. What would you suggest here?

Thanks,
Steven

**Comment by arokem** [comment]
Unless the AFQ browser is specifically important to you, one option is to run `export_all` passing `afqbrowser=False` as a key-word argument (this is set to `True` per default). Even if that does work for you as a stop-gap, we should still think about how we enable this mode of running a group of subjects in parallel - we have discussed this but have not come to a good final solution yet, I think.

**Comment by smeisler** [comment]
I'd like to have browser outputs for all subjects if possible.

**Comment by smeisler** [comment]
Also, I tried to run a single group object with all subjects and introducing parallel params (`parallel_params={"n_jobs": -1, "engine": "joblib", "backend": "loky"}`) and get the following error:


```
Traceback (most recent call last):
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/AFQ/api/group.py", line 312, in __getattribute__
    self.wf_dict[self.valid_sub_list[0]][str(self.valid_ses_list[0])]
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/AFQ/api/group.py", line 312, in __getattribute__
    self.wf_dict[self.valid_sub_list[0]][str(self.valid_ses_list[0])]
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/AFQ/api/group.py", line 312, in __getattribute__
    self.wf_dict[self.valid_sub_list[0]][str(self.valid_ses_list[0])]
  [Previous line repeated 996 more times]
  File "/om2/user/smeisler/anaconda3/envs/pyafq/lib/python3.9/site-packages/AFQ/api/group.py", line 306, in __getattribute__
    return object.__getattribute__(self, attr)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

This persisted after changing the n_jobs to -4 and explicitly increasing the recursion limit:
```
import sys
sys.setrecursionlimit(100000)
```

**Comment by 36000** [comment]
For now, a workaround that will work is to use `GroupAFQ` then call `export_all` with `afqbrowser=False` then call `assemble_AFQ_browser` with `output_path` set to something unique per subject, ie:
```
myafq = GroupAFQ(..., participant_label=[subjectID])
myafq.export_all(afqbrowser=False)
myafq.assemble_AFQ_browser(output_path=f"somepath/{subjectID}_afq_browser")
```

**Comment by 36000** [comment]
I should add an `export_all` method for ParticipantAFQ. If you want to make an AFQBrowser folder from a series of ParticipantAFQ processed subjects, you can call `assemble` from AFQBrowser , which is what GroupAFQ calls:
https://github.com/yeatmanlab/AFQ-Browser/blob/a59a372b207af763bdacfa0127735c23d6033c42/afqbrowser/browser.py#L580

**Comment by 36000** [comment]
the recursion error is a bug I introduced with GroupAFQ, I have made a pull request and it will be fixed in the next release.
