### ISSUE TITLE
Clip to plane ROIs 

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#81]
To get only the central part of the streamline in each individual. See https://github.com/nipy/dipy/pull/1617. 

Alternatively, think of a way to align the nodes across individuals (@jyeatman has ideas how to do this, I believe).

**Comment by kesshijordan** [comment]
Regarding aligning nodes across individuals: One option is doing streamline linear registration to a bundle template in MNI space, and another is just locking it to the anatomy in MNI space. We just have to be careful in thinking about bundles that may vary in where they stop (e.g. the arcuate projects to the cortex on many adjacent gyri and not every case will extend the same distance into the frontal lobe). Simple sub-sampling in the patient's bundle is fine for structures that tend to terminate in a consistent manner (e.g CST, IFOF), but SLF II, III, and Arcuate are bundles for which that method would result in a mismatch between points, anatomically, that may vary considerably depending on parameters/data/age of the subjects. @jyeatman and I discussed approaching the trunk in a tbss-esque analysis, and the periphery using a combination of values and NaN's (the NaN's giving information about how extensively the model is able to track in the periphery; e.g. an arcuate that doesn't extend as far into the frontal lobe in some subjects may indicate low FA, but that depends on the exact model/tracking parameters).

**Comment by 36000** [comment]
Clipping is done in #159 , discussion on realignment can move to #379
