### ISSUE TITLE
Remove underscores in file names

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#819]
With names like: `sub-100206_dwi_space-RASMM_model-DTI_desc-det-AFQ-clean_tractography.trk`
The suffix is only tractography. We should change this so there is no underscore or space or dash, so the suffix is more descriptive. Maybe we should use camelCase?

I would be interested in hearing your thoughts, @arokem ?

**Comment by arokem** [comment]
I believe that we came up with this (addmitedly long) names based on our understanding of the draft of the BIDS derivatives spec for tractography results. That's where that `_tractography` suffix comes from. camelCase is definitely not the BIDS way 😄
