### ISSUE TITLE
How to generate fiber properties of a group and make comparison?

### ISSUE THREAD

**Issue by Roger1219** [yeatmanlab/pyAFQ#821]
Hi experts,
I recently tried to compare the tracts properties (FA, MD) of two groups. The tracts have been generated by mrtrix3. I first used AFQ to process, but it is difficult to covert .nii or .mif file to dt6 format which is acceptable for AFQ in Matlab. Then I found pyAFQ which is updated in recent years. However, there aren't many examples about it. I wonder does it compute fiber properties of groups and make comparison?
Best wishes,
Roger.

**Comment by Roger1219** [comment]
I read the [example](https://yeatmanlab.github.io/pyAFQ/auto_examples/plot_tract_profile.html#sphx-glr-auto-examples-plot-tract-profile-py), but this page shows the plot of a single tract, not tract profile of a group.

**Comment by arokem** [comment]
Hi @Roger1219 : thanks for the question. Statistical analysis (e.g., group differences) is out of the scope of the pyAFQ library. We have also created the [AFQ-Insight](https://github.com/richford/AFQ-Insight) library that handles these kinds of issues. In particular, a function for plotting groups for comparison can be found in https://github.com/richford/AFQ-Insight/blob/main/afqinsight/plot.py#L53. 

Maybe we should improve the documentation to clarify this distinction and direct users to AFQ-Insight more clearly.

**Comment by Roger1219** [comment]
> 
Hi, arokem: Thanks for your help. I read it but it will take some time to know how to use it.

**Comment by 36000** [comment]
This *may* be useful: if you are familiar with AFQ-browser ( https://yeatmanlab.github.io/AFQBrowser-demo/ ) , pyAFQ can assembles an instance of the AFQ-Browser if you are using GroupAFQ. It will show up in the derivatives folder as afq_browser after calling either `export_all` or `assemble_AFQ_browser `.
