### ISSUE TITLE
How to perform fiber clipping ?

### ISSUE THREAD

**Issue by lilingyu0127** [yeatmanlab/pyAFQ#823]
Dear developer,

How can I perfrom **fiber clipping** in pyAFQ using given ROIs?
Thank you!

**Comment by 36000** [comment]
Sorry for the delayed response! If you set clip_edges to True in segmentation_params, as in this example ( https://yeatmanlab.github.io/pyAFQ/auto_examples/plot_afq_callosal.html?highlight=clip ) , it should perform fiber clipping
