### ISSUE TITLE
AttributeError for custom scalars

### ISSUE THREAD

**Issue by jdias001** [yeatmanlab/pyAFQ#824]
I am currently working with dwi data that has been preprocessed in pydesigner and would like to use the scalars output by pydesigner in pyafq. However, when I format the ScalarFile objects for my scalars, giving them a name and the path to the file, I keep getting an AttributeError: 'ScalarFile' object has no attribute 'get_for_subses'. Is there a solution to this problem? My code and the error I receive are below.

    import os
    from glob import glob
    import shutil
    import re
    
    from AFQ.api.participant import ParticipantAFQ
    from AFQ.definitions.scalar import ScalarFile
    
    BIDSfolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\dmriprep\\"
    infolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\derivatives\\pydesigner\\"
    outfolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\derivatives\\afq\\"
    
    dwi_data_files = glob(infolder+"\\**\\ses-*\\*dwi*preprocessed.nii.gz")
    bval_files = glob(infolder+"\\**\\ses-*\\*preprocessed.bval")
    bvec_files = glob(infolder+"\\**\\ses-*\\*preprocessed.bvec")
    
    dki_ak_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_ak*.nii.gz")
    dki_kfa_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_kfa*.nii.gz")
    dki_mk_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_mk*.nii.gz")
    dki_rk_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_rk*.nii.gz")
    dti_ad_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_ad*.nii.gz")
    dti_fa_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_fa*.nii.gz")
    dti_md_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_md*.nii.gz")
    dti_rd_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_rd*.nii.gz")
    
    output_dirs = []
    for dwi_data_file in dwi_data_files:
        output_dir1 = dwi_data_file.replace("pydesigner", "afq")
        if len(output_dir1) == 113:
            output_dir2 = output_dir1.replace(output_dir1[72:127], "")
            output_dirs.append(output_dir2)
        if len(output_dir1) == 123:
            output_dir2 = output_dir1.replace(output_dir1[77:127], "")
            output_dirs.append(output_dir2)
        if len(output_dir1) == 127:
            output_dir2 = output_dir1.replace(output_dir1[79:127], "")
            output_dirs.append(output_dir2)
    
    for x in range(0, len(dwi_data_files)):
        dki_ak_scalar_file = ScalarFile('pd_dki_ak', path = dki_ak_scalar_files[x])
        dki_kfa_scalar_file = ScalarFile('pd_dki_kfa', path = dki_kfa_scalar_files[x])
        dki_mk_scalar_file = ScalarFile('pd_dki_mk', path = dki_mk_scalar_files[x])
        dki_rk_scalar_file = ScalarFile('pd_dki_rk', path = dki_rk_scalar_files[x])
        dti_ad_scalar_file = ScalarFile('pd_dti_ad', path = dti_ad_scalar_files[x])
        dti_fa_scalar_file = ScalarFile('pd_dti_fa', path = dti_fa_scalar_files[x])
        dti_md_scalar_file = ScalarFile('pd_dti_md', path = dti_md_scalar_files[x])
        dti_rd_scalar_file = ScalarFile('pd_dti_rd', path = dti_rd_scalar_files[x])
        
        if not os.path.exists(output_dirs[x]):
            os.makedirs(output_dirs[x])
        
        myafq = ParticipantAFQ(
            dwi_data_file = dwi_data_files[x],
            bval_file = bval_files[x],
            bvec_file = bvec_files[x],
            output_dir = output_dirs[x],
            tractography_params=dict(
                odf_model="DTI"
                ),
            segmentation_params=dict(
                seg_algo="AFQ"
                ),
            scalars=[
                "dti_fa",
                "dti_md",
                "dki_fa",
                "dki_md",
                "dki_awf",
                "dki_mk",
                dki_ak_scalar_file,
                dki_kfa_scalar_file,
                dki_mk_scalar_file,
                dki_rk_scalar_file,
                dti_ad_scalar_file,
                dti_fa_scalar_file,
                dti_md_scalar_file,
                dti_rd_scalar_file
                ]
           )
        shutil.copy(r'C:\Users\james\Documents\DKI\pyAFQ\Template Images\tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz',r'C:\Users\james\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz')
        shutil.copy(r'C:\Users\james\Documents\DKI\pyAFQ\Template Images\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz',r'C:\Users\james\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz')
        myafq.export_all()

Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "C:\Users\james\AppData\Local\Programs\Python\Python38\lib\site-packages\AFQ\api\participant.py", line 101, in __init__
    "mapping": get_mapping_plan(kwargs),
  File "C:\Users\james\AppData\Local\Programs\Python\Python38\lib\site-packages\AFQ\tasks\mapping.py", line 257, in get_mapping_plan
    pimms.calc(f"{scalar.name}_file")(scalar.get_for_subses())
AttributeError: 'ScalarFile' object has no attribute 'get_for_subses'

**Comment by 36000** [comment]
Your code looks correct! I believe this is a typo in 0.11 . We have two options.

One, install pyAFQ from github master where this is fixed, and you would use `ImageFile ` from `from AFQ.definitions.image import ImageFile `. This may be the better option, because if you run into any errors resulting from running on Windows we can fix them on master quickly. We should work on Windows but it is less tested.

Two, we hotfix by pasting in a corrected `ScalarFile ` (this could just go near top of your script) instead of importing the bugged one from `AFQ.definitions.scalar `:

from AFQ.definitions.mask import MaskFile
from AFQ.definitions.scalar import ScalarMixin

class ScalarFile(ScalarMixin, MaskFile):
    def __init__(self, name, path=None, suffix=None, filters={}):
        MaskFile.__init__(self, path, suffix, filters)
        self.name = name

    def get_data(self, subses_dict, bids_info, dwi_affine,
                 reg_template, mapping):
        if self.from_path:
            return self.fname
        else:
            return self.fnames[bids_info['session']][bids_info['subject']]

Thank you for pasting the code and traceback, and let me know when you try either of this options and whether they work.

**Comment by jdias001** [comment]
I'm going to use the first option. Before I run the script, however, how will the scalars be labeled in the output? ImageFile, which it seems will replace ScalarFile, does not include a "name", only a path.

Thank you for your quick response to these issues.

**Comment by 36000** [comment]
Yes, this is the code used to determine it now:
```
def name_from_path(path):
    file_name = op.basename(path)  # get file name
    file_name = drop_extension(file_name)  # remove extension
    if "-" in file_name:
        file_name = file_name.split("-")[-1]  # get suffix if exists
    return file_name
```

**Comment by jdias001** [comment]
There is a new error:

    import os
    from glob import glob
    import shutil
    import re
    
    from AFQ.api.participant import ParticipantAFQ
    # from AFQ.definitions.scalar import ScalarFile
    from AFQ.definitions.image import ImageFile
    
    BIDSfolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\dmriprep\\"
    infolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\derivatives\\pydesigner\\"
    outfolder = "C:\\Users\\james\\Documents\\DKI\\pyAFQ\\BIDS\\derivatives\\afq\\"
    
    dwi_data_files = glob(infolder+"\\**\\ses-*\\*dwi*preprocessed.nii.gz")
    bval_files = glob(infolder+"\\**\\ses-*\\*preprocessed.bval")
    bvec_files = glob(infolder+"\\**\\ses-*\\*preprocessed.bvec")
    
    dki_ak_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_ak*.nii.gz")
    dki_kfa_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_kfa*.nii.gz")
    dki_mk_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_mk*.nii.gz")
    dki_rk_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dki_rk*.nii.gz")
    dti_ad_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_ad*.nii.gz")
    dti_fa_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_fa*.nii.gz")
    dti_md_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_md*.nii.gz")
    dti_rd_scalar_files = glob(infolder+"\\**\\ses-*\\metrics\\*dti_rd*.nii.gz")
    
    output_dirs = []
    for dwi_data_file in dwi_data_files:
        output_dir1 = dwi_data_file.replace("pydesigner", "afq")
        if len(output_dir1) == 113:
            output_dir2 = output_dir1.replace(output_dir1[72:127], "")
            output_dirs.append(output_dir2)
        if len(output_dir1) == 123:
            output_dir2 = output_dir1.replace(output_dir1[77:127], "")
            output_dirs.append(output_dir2)
        if len(output_dir1) == 127:
            output_dir2 = output_dir1.replace(output_dir1[79:127], "")
            output_dirs.append(output_dir2)
    
    for x in range(0, len(dwi_data_files)):
        # dki_ak_scalar_file = ScalarFile('pd_dki_ak', path = dki_ak_scalar_files[x])
        # dki_kfa_scalar_file = ScalarFile('pd_dki_kfa', path = dki_kfa_scalar_files[x])
        # dki_mk_scalar_file = ScalarFile('pd_dki_mk', path = dki_mk_scalar_files[x])
        # dki_rk_scalar_file = ScalarFile('pd_dki_rk', path = dki_rk_scalar_files[x])
        # dti_ad_scalar_file = ScalarFile('pd_dti_ad', path = dti_ad_scalar_files[x])
        # dti_fa_scalar_file = ScalarFile('pd_dti_fa', path = dti_fa_scalar_files[x])
        # dti_md_scalar_file = ScalarFile('pd_dti_md', path = dti_md_scalar_files[x])
        # dti_rd_scalar_file = ScalarFile('pd_dti_rd', path = dti_rd_scalar_files[x])
        dki_ak_scalar_file = ImageFile(path = dki_ak_scalar_files[x])
        dki_kfa_scalar_file = ImageFile(path = dki_kfa_scalar_files[x])
        dki_mk_scalar_file = ImageFile(path = dki_mk_scalar_files[x])
        dki_rk_scalar_file = ImageFile(path = dki_rk_scalar_files[x])
        dti_ad_scalar_file = ImageFile(path = dti_ad_scalar_files[x])
        dti_fa_scalar_file = ImageFile(path = dti_fa_scalar_files[x])
        dti_md_scalar_file = ImageFile(path = dti_md_scalar_files[x])
        dti_rd_scalar_file = ImageFile(path = dti_rd_scalar_files[x])
        
        if not os.path.exists(output_dirs[x]):
            os.makedirs(output_dirs[x])
        
        myafq = ParticipantAFQ(
            dwi_data_file = dwi_data_files[x],
            bval_file = bval_files[x],
            bvec_file = bvec_files[x],
            output_dir = output_dirs[x],
            tractography_params=dict(
                # directions="det",
                # max_angle=30,
                # sphere=None,
                # seed_mask=None,
                # seed_threshold=0,
                # n_seeds=1,
                # random_seeds=False,
                # rng_seed=None,
                # stop_mask=None,
                # stop_threshold=0,
                # step_size=0.5,
                # min_length=10,
                # max_length=1000,
                odf_model="DTI"
                # tracker="local"
                ),
            segmentation_params=dict(
                # nb_points=False,
                # nb_streamlines=False,
                seg_algo="AFQ"
                # reg_algo=None,
                # clip_edges=False,
                # parallel_segmentation="{'n_jobs': -1, 'engine': 'joblib', 'backend': 'loky'}",
                # progressive=True,             # for reco80
                # greater_than=50,              # for reco80
                # rm_small_clusters=50,         # for reco80
                # model_clust_thr=1.25,         # for reco80
                # reduction_thr=25,             # for reco80
                # refine=False,                 # for reco80
                # pruning_thr=12,               # for reco80
                # b0_threshold=50,              # for afq
                # prob_threshold=0,             # for afq
                # roi_dist_tie_break=False,     # for afq
                # dist_to_waypoint=None,        # for afq
                # rng=None,                     # for reco80
                # return_idx=False,
                # presegment_bundle_dict=None,
                # presegment_kawrgs="{}",
                # filter_by_endpoints=True,
                # dist_to_atlas=4,
                # save_intermediates=None
                ),
            # cleaning_params=dict(
            #     n_points=100,
            #     clean_round=5,
            #     distance_threshold=5,           # default = 5
            #     length_threshold=4,             # default = 4
            #     min_sl=20,                      # default = 20
            #     stat="mean",
            #     # return_idx=False
            #     ),
            # data=dict(
            #     # min_bval=None,
            #     # max_bval=None,
            #     # filter_b=True,
            #     # b0_threshold=50,
            #     # robust_tensor_fitting=False,
            #     # csd_response=None,
            #     # csd_sh_order=None,
            #     # csd_lamda_=1,
            #     # csd_tau=0.1,
            #     # shpere="repulsion100",
            #     # gtol=0.01,
            #     # brain_mask_definition=None,
            #     # bundle_info=None,
            #     # reg_template_spec="mni_T1"
            #     ),
            # mapping=dict(
            #     # mapping_definition=None,
            #     # reg_subject_spec="power_map"
            #     ),
            # segmentation=dict(
            # profile_weights="gauss",
            scalars=[
                "dti_fa",
                "dti_md",
                "dki_fa",
                "dki_md",
                "dki_awf",
                "dki_mk",
                dki_ak_scalar_file,
                dki_kfa_scalar_file,
                dki_mk_scalar_file,
                dki_rk_scalar_file,
                dti_ad_scalar_file,
                dti_fa_scalar_file,
                dti_md_scalar_file,
                dti_rd_scalar_file
                ]
                # )
            # tractography=dict(
            #     # import_tract=None
            #     ),
            # viz=dict(
            #     # sbv_lims_bundles=[None,None],
            #     # volume_opacity_bundles=0.3,
            #     # n_points_bundles=40,
            #     # sbv_lims_indiv=[None,None],
            #     # volume_opacity_indiv=0.3,
            #     # n_points_indiv=40,
            #     # viz_backend_spec="plotly_no_gif",
            #     # virtual_frame_buffer=False
            #     )
           )
        shutil.copy(r'C:\Users\james\Documents\DKI\pyAFQ\Template Images\tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz',r'C:\Users\james\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz')
        shutil.copy(r'C:\Users\james\Documents\DKI\pyAFQ\Template Images\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz',r'C:\Users\james\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz')
        myafq.export_all()

runcell('Testing participant-level processing of DKI data', 'C:/Users/james/Documents/DKI/pyAFQ/pyAFQ_Processing_v1b.py')
Traceback (most recent call last):

  File "C:\Program Files\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\james\documents\dki\pyafq\pyafq_processing_v1b.py", line 177, in <module>
    myafq = ParticipantAFQ(

  File "C:\Users\james\AppData\Local\Programs\Python\Python38\Lib\site-packages\AFQ\api\participant.py", line 101, in __init__
    "mapping": get_mapping_plan(kwargs),

  File "C:\Users\james\AppData\Local\Programs\Python\Python38\Lib\site-packages\AFQ\tasks\mapping.py", line 258, in get_mapping_plan
    pimms.calc(f"{scalar.get_name()}_file")(

  File "C:\Users\james\AppData\Local\Programs\Python\Python38\Lib\site-packages\AFQ\definitions\image.py", line 156, in get_name
    if self.suffix is not None:

AttributeError: 'ImageFile' object has no attribute 'suffix'



I'll note that I did include a suffix for the scalar files, but it returned the same error.

**Comment by 36000** [comment]
Sorry about this, I updated master & added a test for this, so if you install from master it should fix this problem.

**Comment by jdias001** [comment]
The code is working now and using the custom scalars from pydesigner. However, I now have an issue with the output that I'll report as a new issue.
