### ISSUE TITLE
error running RecoBundles80 using AFQ API on google colab

### ISSUE THREAD

**Issue by artzimy** [yeatmanlab/pyAFQ#837]
runing plot_afq_reco80.ipynb on google colab, I got the following error:
bundle_html = myafq.export("all_bundles_figure")
plotly.io.show(bundle_html["01"])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-4842a2c37ca4>](https://localhost:8080/#) in <module>()
----> 1 bundle_html = myafq.export("all_bundles_figure")
      2 plotly.io.show(bundle_html["01"])

[/usr/local/lib/python3.7/dist-packages/AFQ/api/group.py](https://localhost:8080/#) in __getattribute__(self, attr)
    336         # attr not found, allow typical AttributeError
    337         if attr_name is None:
--> 338             return object.__getattribute__(self, attr)
    339 
    340         # iterate over subjects / sessions,

AttributeError: 'GroupAFQ' object has no attribute 'export'

how to resolve?
Thanks moran

**Comment by 36000** [comment]
What version of pyAFQ are you using? Only the most recent version of pyAFQ has that attribute. In previous versions it would be myafq. export_all_bundles_figure() I believe.

**Comment by artzimy** [comment]
Thanks!
myafq. export_all_bundles_figure()    works
and Im using V 0.11

**Comment by 36000** [comment]
The API will stabilize once we do our 1.0 release soon. Thank you for using pyAFQ!
