### ISSUE TITLE
Document baby AFQ

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#841]
AFAIK, this is the closest we have to such documentation at the moment: https://github.com/bloomdt-uw/babyafq/blob/main/baby_afq.py, and that's not up-to-date with the current API.

**Comment by 36000** [comment]
We now have an example: https://github.com/yeatmanlab/pyAFQ/blob/fb3c261e74408dc277cbef5a7462ba1c5487b6e0/examples/howto_examples/baby_afq.py
