### ISSUE TITLE
move computation within while loop for cleaning

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#888]
Shouldn't this move to the top of the while loop and then remove line 1101?
https://github.com/yeatmanlab/pyAFQ/blob/3cbcf12e194ae40bd1502970a39ab62604aae669/AFQ/segmentation.py#L1078

**Comment by 36000** [comment]
We want to calculate this before doing the checks on the while loop. We could make it one call by moving while loop checks into an if statement, which breaks from loop if true. It’s a matter of preference as  python does not have do-while loops, ie:


while True:
  stuff()
  if fail_condition:
    break

Or:

stuff()
while not fail_condition:
  stuff()

**Comment by 36000** [comment]
Based on the fact that we clearly have a bug where we pass stat in one place and not another, I think it makes sense to change to the “if fail_condition” structure
