### ISSUE TITLE
undocumented argument stat=stat

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#889]
When this is used earlier the argument stat is set to stat=stat but here we use the default. Does that take the mean across fibers?
https://github.com/yeatmanlab/pyAFQ/blob/3cbcf12e194ae40bd1502970a39ab62604aae669/AFQ/segmentation.py#L1101

DIPY documentation is unclear: https://dipy.org/documentation/1.4.1./reference/dipy.stats/#gaussian-weights

Also, double check that we're calculating mahalanobis distance not weight which is the inverse

**Comment by 36000** [comment]
The dipy documentation here needs updated. looking at the actual code, I think it is doing the right thing: https://github.com/dipy/dipy/blob/f0775487bf01eee8964f5224e176ec99c891da0e/dipy/stats/analysis.py#L149
