### ISSUE TITLE
clobber

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/pyAFQ#891]
AFQ object should have a clobber option

**Comment by arokem** [comment]
Different from what's already implemented in https://github.com/yeatmanlab/pyAFQ/pull/853? How different?

**Comment by 36000** [comment]
current solution: https://github.com/yeatmanlab/pyAFQ/blob/a71bcb051918f8e85fc86f04ecc1932f53a37eff/AFQ/api/group.py#L517 

ie, cmd_outputs deemed not intuitive enough. also some minor bf to cmd_outputs have been done.
