### ISSUE TITLE
Should we make s3bids its own library? 

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#908]
Unless I am missing something, it seems to have only rather tenuous dependencies on the rest of pyAFQ, and I can imagine use-cases outside of pyAFQ, where the pyAFQ dependencies may be considered onerous.

**Comment by arokem** [comment]
I forgot about https://github.com/nrdg/cloud_bids_layout, which should eventually evolve into that. 

For the time being, I wonder whether we should add some kind of warning to the s3bids module here, to communicate that this will eventually become its own freestanding thing. 

If we want to do that, might be good to do that for the 1.0 release, so that anyone using this knows that this will not be a long-standing feature they can depend on.

**Comment by 36000** [comment]
Closed by #1109
