### ISSUE TITLE
`parallel_params` not passed into segmentation

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#917]
I think that the `parallel_params` variable from the `GroupAFQ` is not properly passed into the `Segmentation` object. The reason I think this is that I am looking at a crash in segmentation (for another reason) in a `GroupAFQ` object that has the default set for the `parallel_params` and the stack trace from segmentation is arising from this line: https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/segmentation.py#L680, which suggests that we are using the default of the `Segmentation` object, and not the default of the `GroupAFQ` object.

**Comment by arokem** [comment]
Oh - I see - we need to use the `parallel_segmentation` input to `GroupAFQ`. Not an issue, but pretty confusing :-)

**Comment by arokem** [comment]
Actually - reopened, because even when setting `parallel_segmentation = {"engine": "serial"}` we still end up in the parallelized code anyway

**Comment by 36000** [comment]
Did you put this in segmentation_params?
IE `segmentation_params={"parallel_segmentation": {"engine": "serial"}}`

**Comment by arokem** [comment]
No. We tried to pass `parallel_segmentation = {"engine": "serial"}` as a kwarg to the initialized, but I get it now.

**Comment by 36000** [comment]
I should make it so unrecognized kwargs throw an error.
