### ISSUE TITLE
a error when downloading template 

### ISSUE THREAD

**Issue by RosieZho** [yeatmanlab/pyAFQ#924]
When I use pyAFQ to process my data, the terminal prints "nibabel.filebasedimages.ImageFileError: File C:\Users\Leqing Zhou\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz is not a gzip file" .
      Then I check the directory. It seems that I can not download the right file from [https://templateflow.s3.amazonaws.com/.]

**Comment by arokem** [comment]
Thanks for reporting! This seems like a templateflow issue, and is the kind of thing that can be intermittent. 

I would remove the cache directory and give it another try, in case something went wrong in the data transmission the first time you tried it.

**Comment by RosieZho** [comment]
I have tried to remove the cache directory and run the code, but it don't work. Maybe it be the problem in the templateflow website?

**Comment by 66RuixiZheng** [comment]
I met the same problem,have you solved it?

**Comment by RosieZho** [comment]
Not yet. I change to use the matlab version. Maybe you can try to report the problem in the templateflow website.

**Comment by 66RuixiZheng** [comment]
Thank you very much!

**Comment by 66RuixiZheng** [comment]
Can you tell me about your computer's operating system? win? macos? I'm trying to figure out if it's a difference in computer systems that's preventing the code from working properly.

**Comment by arokem** [comment]
Closing as superseded by [this issue](https://github.com/templateflow/python-client/issues/108) on templateflow.
