### ISSUE TITLE
[BUG] Should this have a tilde?

### ISSUE THREAD

**Issue by 36000** [yeatmanlab/pyAFQ#950]
https://github.com/yeatmanlab/pyAFQ/blob/afcc50caa8d58da35570e0bca64091ffbf406035/AFQ/tasks/data.py#L87

I think this is actually calculating the mean when b!=0. The tilde should be removed. For example, in the current setup the ventricles are dark but if the tilde is removed, the ventricles are white, as they should be in a b0.

@arokem  does this make sense?

**Comment by arokem** [comment]
Yes. Good catch!
