### ISSUE TITLE
Export just the maps

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#957]
We want to do experiments where we run several different tractography parameters on the same dataset. But we'd like to save the time on calculating the non-tractography derivatives (e.g., model parameters, maps of the scalars, registrations, etc.). To run this through qsiprep, we would want this all to be one export command, but I don't think that we have any export rule right now that is "give me everything that doesn't require tractography", do we?

**Comment by 36000** [comment]
Nope! You would just do a series of export commands. Something like:
```
myafq.export("csd_params")
myafq.export("mapping")
myafq.export("dti_fa")
myafq.export("dti_md")
```

**Comment by 36000** [comment]
this can now also be done with:
`myafq.export_up_to("streamlines")`
