### ISSUE TITLE
no bundles?

### ISSUE THREAD

**Issue by sleeeeeeepy** [yeatmanlab/pyAFQ#960]
Hello,

Thank you very much for your detailed answer to my question the other day, we were able to perform tractometry automatically using pyAFQ.
However, one problem arose.
When we looked at the html results, one subject did not have all 22 fibers (missing ATR-R, etc.). 
And when we looked in the "viz_core_bundles" folder, 22 fibers were not extracted. 
How can we get all 22 n fibers to be extracted?
We will describe how we did the command in "jupyternotebook".

import os
os.getcwd()

from AFQ.api.participant import ParticipantAFQ

output_directory_WMH_0000 = "./WMH_0000/tract_WMH_0000"

myafq_WMH_0000 = ParticipantAFQ(
    "./WMH_0000/WMH_0000_dwi_den_unr_preproc_unbiased.nii.gz",
    "./WMH_0000/WMH_0000.bval",
    "./WMH_0000/WMH_0000.bvec",
    output_dir = output_directory_WMH_0000)

myafq_WMH_0000.export_all()

Best regards,

**Comment by arokem** [comment]
Is this an issue with just on subject out of a dataset? Is there something unusual about this subject's data? This kind of thing happens sometimes when the registration of the subject data to the template fails for some reason, so I would look at the output file that has the "_template_dwi.nii.gz" suffix in this subject's outputs folder and see whether the template looks badly warped. That might provide some clue about what happened.

**Comment by sleeeeeeepy** [comment]
Thank you very much for your kind reply, the problem occurred in about 30 out of 100 subjects. Now that I don't have the resulting files at hand, I will look at the "_template_dwi.nii.gz" file later to see if there is any distortion in the images and ask you how to better warp them (i.e. how to use T1 enhanced images if not in BIDS format).
Best regards,

**Comment by sleeeeeeepy** [comment]
As you say, I found that the left frontal lobe is badly warped by looking at the output file with the suffix "_template_dwi.nii.gz" in the outputs folder of this subject. I assumed that the use of T1-enhanced images would improve the registration of the subject data to the template, but is it possible to use T1-enhanced images in this software if they are not in BIDS format?
Best regards,

**Comment by arokem** [comment]
Sorry for the long pause here - I just realized that we never replied to this question. The answer is that it is possible to use data not in BIDS, but you'd need to write quite a bit of your own code to make that happen. I'd generally recommend putting your T1w data into a BIDS-compliant format for this purpose, since it will make running the software much easier. Given how long it's been, I'll close this issue, but feel free to reopen if you still need more input from us.
