### ISSUE TITLE
OSError and URLError in myafq.export

### ISSUE THREAD

**Issue by snaillyd** [yeatmanlab/pyAFQ#967]
I tried to run the example code of RecoBundles80 using AFQ API 

bundle_html = myafq.export("all_bundles_figure")

I got errors like this when running the above command！

----->
OSError                                   Traceback (most recent call last)
File ~/anaconda3/lib/python3.10/urllib/request.py:1348, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1347 try:
-> 1348     h.request(req.get_method(), req.selector, req.data, headers,
   1349               encode_chunked=req.has_header('Transfer-encoding'))
   1350 except OSError as err: # timeout error

File ~/anaconda3/lib/python3.10/http/client.py:1282, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1281 """Send a complete request to the server."""
-> 1282 self._send_request(method, url, body, headers, encode_chunked)

File ~/anaconda3/lib/python3.10/http/client.py:1328, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1327     body = _encode(body, 'body')
-> 1328 self.endheaders(body, encode_chunked=encode_chunked)

File ~/anaconda3/lib/python3.10/http/client.py:1277, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1276     raise CannotSendHeader()
-> 1277 self._send_output(message_body, encode_chunked=encode_chunked)

File ~/anaconda3/lib/python3.10/http/client.py:1037, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1036 del self._buffer[:]
-> 1037 self.send(msg)
   1039 if message_body is not None:
   1040 
   1041     # create a consistent interface to message_body

File ~/anaconda3/lib/python3.10/http/client.py:975, in HTTPConnection.send(self, data)
    974 if self.auto_open:
--> 975     self.connect()
    976 else:

File ~/anaconda3/lib/python3.10/http/client.py:1447, in HTTPSConnection.connect(self)
   1445 "Connect to a host on a given (SSL) port."
-> 1447 super().connect()
   1449 if self._tunnel_host:

File ~/anaconda3/lib/python3.10/http/client.py:941, in HTTPConnection.connect(self)
    940 sys.audit("http.client.connect", self, self.host, self.port)
--> 941 self.sock = self._create_connection(
    942     (self.host,self.port), self.timeout, self.source_address)
    943 # Might fail in OSs that don't implement TCP_NODELAY

File ~/anaconda3/lib/python3.10/socket.py:845, in create_connection(address, timeout, source_address)
    844 try:
--> 845     raise err
    846 finally:
    847     # Break explicitly a reference cycle

File ~/anaconda3/lib/python3.10/socket.py:833, in create_connection(address, timeout, source_address)
    832     sock.bind(source_address)
--> 833 sock.connect(sa)
    834 # Break explicitly a reference cycle

OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
Cell In[6], line 1
----> 1 bundle_html = myafq.export("all_bundles_figure")

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/group.py:431, in GroupAFQ.export(self, attr_name, collapse)
    429         to_calc_list.append((subject, session))
    430     else:
--> 431         results[subject][session] = wf_dict[attr_name]
    433 # if some need to be calculated, do those in parallel
    434 if to_calc_list:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:91, in Calc.__call__(self, *args, **kwargs)
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
     90     args.append(opts[name])
---> 91 result = self.function(*args)
     92 if is_map(result):
     93     if len(result) != len(self.efferents) or not all(e in result for e in self.efferents):

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/viz.py:80, in viz_bundles(base_fname, dwi_affine, viz_backend, data_imap, mapping_imap, segmentation_imap, tracking_params, segmentation_params, best_scalar, sbv_lims_bundles, volume_opacity_bundles, n_points_bundles)
     78 bundle_dict = data_imap["bundle_dict"]
     79 scalar_dict = segmentation_imap["scalar_dict"]
---> 80 profiles_file = segmentation_imap["profiles"]
     81 volume = data_imap["b0"]
     82 shade_by_volume = data_imap[best_scalar]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:90, in Calc.__call__(self, *args, **kwargs)
     88     if name not in opts:
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
---> 90     args.append(opts[name])
     91 result = self.function(*args)
     92 if is_map(result):

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:856, in LazyPMap.__getitem__(self, k)
    855 def __getitem__(self, k):
--> 856     return self._examine_val(k, ps.PMap.__getitem__(self, k))

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:852, in LazyPMap._examine_val(self, k, val)
    850     return val
    851 else:
--> 852     val = val()
    853     object.__setattr__(self, '_memoized', self._memoized.set(vid, val))
    854     return val

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1131, in merge.<locals>.curry_choice.<locals>.<lambda>()
-> 1131 def curry_choice(k, args): return lambda:choose_fn(k, args)

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1100, in _choose_last(k, vs)
   1098 def _choose_last(k, vs):
   1099     '_choose_last(k, vs) yields vs[-1][k].'
-> 1100     return vs[-1][k]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:90, in Calc.__call__(self, *args, **kwargs)
     88     if name not in opts:
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
---> 90     args.append(opts[name])
     91 result = self.function(*args)
     92 if is_map(result):

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:856, in LazyPMap.__getitem__(self, k)
    855 def __getitem__(self, k):
--> 856     return self._examine_val(k, ps.PMap.__getitem__(self, k))

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:852, in LazyPMap._examine_val(self, k, val)
    850     return val
    851 else:
--> 852     val = val()
    853     object.__setattr__(self, '_memoized', self._memoized.set(vid, val))
    854     return val

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1131, in merge.<locals>.curry_choice.<locals>.<lambda>()
-> 1131 def curry_choice(k, args): return lambda:choose_fn(k, args)

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1100, in _choose_last(k, vs)
   1098 def _choose_last(k, vs):
   1099     '_choose_last(k, vs) yields vs[-1][k].'
-> 1100     return vs[-1][k]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:91, in Calc.__call__(self, *args, **kwargs)
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
     90     args.append(opts[name])
---> 91 result = self.function(*args)
     92 if is_map(result):
     93     if len(result) != len(self.efferents) or not all(e in result for e in self.efferents):

File <string>:2, in wrapper_has_args_func(dwi, data_imap, mapping_imap, tractography_imap, segmentation_params, base_fname, tracking_params)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/decorators.py:133, in as_file.<locals>._as_file.<locals>.wrapper_as_file(*args, **kwargs)
    128 this_file = get_fname(
    129     base_fname, suffix,
    130     tracking_params=tracking_params,
    131     segmentation_params=segmentation_params)
    132 if not op.exists(this_file):
--> 133     img_trk_np_or_csv, meta = func(*args[:og_arg_count], **kwargs)
    135     logger.info(f"Saving {this_file}")
    136     if isinstance(img_trk_np_or_csv, nib.Nifti1Image):

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/segmentation.py:60, in segment(dwi, data_imap, mapping_imap, tractography_imap, segmentation_params)
     58 start_time = time()
     59 segmentation = seg.Segmentation(**segmentation_params)
---> 60 bundles = segmentation.segment(
     61     bundle_dict,
     62     tg,
     63     dwi,
     64     data_imap["bval"],
     65     data_imap["bvec"],
     66     reg_template=reg_template,
     67     mapping=mapping_imap["mapping"])
     69 seg_sft = aus.SegmentedSFT(bundles, Space.VOX)
     71 if len(seg_sft.sft) < 1:

File ~/anaconda3/lib/python3.10/site-packages/AFQ/segmentation.py:347, in Segmentation.segment(self, bundle_dict, tg, fdata, fbval, fbvec, mapping, reg_prealign, reg_template, img_affine, reset_tg_space)
    345     fiber_groups = self.segment_afq()
    346 elif self.seg_algo.startswith("reco"):
--> 347     fiber_groups = self.segment_reco()
    348 else:
    349     raise ValueError(f"The seg_algo input is {self.seg_algo}, which",
    350                      "is not recognized")

File ~/anaconda3/lib/python3.10/site-packages/AFQ/segmentation.py:954, in Segmentation.segment_reco(self, tg)
    952     rb = RecoBundles(self.moved_sl, verbose=False, rng=self.rng)
    953 # Next we'll iterate over bundles, registering each one:
--> 954 bundle_list = list(self.bundle_dict.keys())
    955 if 'whole_brain' in bundle_list:
    956     bundle_list.remove('whole_brain')

File ~/anaconda3/lib/python3.10/_collections_abc.py:886, in KeysView.__iter__(self)
    885 def __iter__(self):
--> 886     yield from self._mapping

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:373, in BundleDict.__iter__(self)
    372 def __iter__(self):
--> 373     self.gen_all()
    374     return iter(self._dict)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:308, in BundleDict.gen_all(self)
    306     if bundle_name not in self._dict:
    307         if not self.templates_loaded:
--> 308             self.load_templates()
    309         self._gen(bundle_name)
    310 if self.templates_loaded:

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:219, in BundleDict.load_templates(self)
    217 elif self.seg_algo.startswith("reco"):
    218     if self.seg_algo.endswith("80"):
--> 219         self.templates = afd.read_hcp_atlas(80, as_file=True)
    220     else:
    221         self.templates = afd.read_hcp_atlas(16, as_file=True)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/data/fetch.py:925, in read_hcp_atlas(n_bundles, as_file)
    923     atlas_folder = "Atlas_in_MNI_Space_16_bundles"
    924 elif n_bundles == 80:
--> 925     _, folder = fetch_hcp_atlas_80_bundles()
    926     atlas_folder = "Atlas_80_Bundles"
    928 whole_brain = op.join(
    929     folder,
    930     atlas_folder,
    931     'whole_brain',
    932     'whole_brain_MNI.trk')

File ~/anaconda3/lib/python3.10/site-packages/AFQ/data/fetch.py:78, in _make_reusable_fetcher.<locals>.fetcher()
     76     return files, folder
     77 else:
---> 78     return _make_fetcher(
     79         name, folder, baseurl, remote_fnames, local_fnames,
     80         doc=doc, **make_fetcher_kwargs)()

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:197, in _make_fetcher.<locals>.fetcher()
    194 for i, (f, n), in enumerate(zip(remote_fnames, local_fnames)):
    195     files[n] = (baseurl + f, md5_list[i] if
    196                 md5_list is not None else None)
--> 197 fetch_data(files, folder, data_size)
    199 if msg is not None:
    200     _log(msg)

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:146, in fetch_data(files, folder, data_size)
    144     all_skip = False
    145     _log('Downloading "%s" to %s' % (f, folder))
--> 146     _get_file_data(fullpath, url)
    147     check_md5(fullpath, md5)
    148 if all_skip:

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:96, in _get_file_data(fname, url)
     95 def _get_file_data(fname, url):
---> 96     with contextlib.closing(urlopen(url)) as opener:
     97         try:
     98             response_size = opener.headers['content-length']

File ~/anaconda3/lib/python3.10/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File ~/anaconda3/lib/python3.10/urllib/request.py:519, in OpenerDirector.open(self, fullurl, data, timeout)
    516     req = meth(req)
    518 sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 519 response = self._open(req, data)
    521 # post-process response
    522 meth_name = protocol+"_response"

File ~/anaconda3/lib/python3.10/urllib/request.py:536, in OpenerDirector._open(self, req, data)
    533     return result
    535 protocol = req.type
--> 536 result = self._call_chain(self.handle_open, protocol, protocol +
    537                           '_open', req)
    538 if result:
    539     return result

File ~/anaconda3/lib/python3.10/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File ~/anaconda3/lib/python3.10/urllib/request.py:1391, in HTTPSHandler.https_open(self, req)
   1390 def https_open(self, req):
-> 1391     return self.do_open(http.client.HTTPSConnection, req,
   1392         context=self._context, check_hostname=self._check_hostname)

File ~/anaconda3/lib/python3.10/urllib/request.py:1351, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1348         h.request(req.get_method(), req.selector, req.data, headers,
   1349                   encode_chunked=req.has_header('Transfer-encoding'))
   1350     except OSError as err: # timeout error
-> 1351         raise URLError(err)
   1352     r = h.getresponse()
   1353 except:

URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by snaillyd** [comment]
how can i solve this problem?  Thanks!

**Comment by arokem** [comment]
Are you running on a computer that is connected to the internet? I think that might be required to run this, at least for the first time.

**Comment by snaillyd** [comment]
Yes，I tried the same codes on two PCs（utunbu 20.04 and windows 10）which are all connected to the internet， and got the same errors.

The followings are the new errors I got yesterday:
HTTPError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 bundle_html = myafq.export("all_bundles_figure")

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/group.py:431, in GroupAFQ.export(self, attr_name, collapse)
    429         to_calc_list.append((subject, session))
    430     else:
--> 431         results[subject][session] = wf_dict[attr_name]
    433 # if some need to be calculated, do those in parallel
    434 if to_calc_list:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:91, in Calc.__call__(self, *args, **kwargs)
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
     90     args.append(opts[name])
---> 91 result = self.function(*args)
     92 if is_map(result):
     93     if len(result) != len(self.efferents) or not all(e in result for e in self.efferents):

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/viz.py:80, in viz_bundles(base_fname, dwi_affine, viz_backend, data_imap, mapping_imap, segmentation_imap, tracking_params, segmentation_params, best_scalar, sbv_lims_bundles, volume_opacity_bundles, n_points_bundles)
     78 bundle_dict = data_imap["bundle_dict"]
     79 scalar_dict = segmentation_imap["scalar_dict"]
---> 80 profiles_file = segmentation_imap["profiles"]
     81 volume = data_imap["b0"]
     82 shade_by_volume = data_imap[best_scalar]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:90, in Calc.__call__(self, *args, **kwargs)
     88     if name not in opts:
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
---> 90     args.append(opts[name])
     91 result = self.function(*args)
     92 if is_map(result):

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:856, in LazyPMap.__getitem__(self, k)
    855 def __getitem__(self, k):
--> 856     return self._examine_val(k, ps.PMap.__getitem__(self, k))

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:852, in LazyPMap._examine_val(self, k, val)
    850     return val
    851 else:
--> 852     val = val()
    853     object.__setattr__(self, '_memoized', self._memoized.set(vid, val))
    854     return val

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1131, in merge.<locals>.curry_choice.<locals>.<lambda>()
-> 1131 def curry_choice(k, args): return lambda:choose_fn(k, args)

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1100, in _choose_last(k, vs)
   1098 def _choose_last(k, vs):
   1099     '_choose_last(k, vs) yields vs[-1][k].'
-> 1100     return vs[-1][k]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:90, in Calc.__call__(self, *args, **kwargs)
     88     if name not in opts:
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
---> 90     args.append(opts[name])
     91 result = self.function(*args)
     92 if is_map(result):

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:856, in LazyPMap.__getitem__(self, k)
    855 def __getitem__(self, k):
--> 856     return self._examine_val(k, ps.PMap.__getitem__(self, k))

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:852, in LazyPMap._examine_val(self, k, val)
    850     return val
    851 else:
--> 852     val = val()
    853     object.__setattr__(self, '_memoized', self._memoized.set(vid, val))
    854     return val

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1131, in merge.<locals>.curry_choice.<locals>.<lambda>()
-> 1131 def curry_choice(k, args): return lambda:choose_fn(k, args)

File ~/anaconda3/lib/python3.10/site-packages/pimms/util.py:1100, in _choose_last(k, vs)
   1098 def _choose_last(k, vs):
   1099     '_choose_last(k, vs) yields vs[-1][k].'
-> 1100     return vs[-1][k]

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:470, in IMap.__getitem__(self, k)
    468 effval = self.efferents.get(k, self)
    469 if effval is self:
--> 470     self._run_node(self.plan.efferents[k])
    471     return self.efferents[k]
    472 else:

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:534, in IMap._run_node(self, node)
    531     else: cpath = None
    532     #except Exception: #(h, found) = (None, False)
    533 # ensure we have a result
--> 534 if not found: res = node(self)
    535 # process the result:
    536 effs = reduce(lambda m,v: m.set(v[0],v[1]), six.iteritems(res), self.efferents)

File ~/anaconda3/lib/python3.10/site-packages/pimms/calculation.py:91, in Calc.__call__(self, *args, **kwargs)
     89         raise ValueError('required parameter %s not given to %s' % (name, self.name))
     90     args.append(opts[name])
---> 91 result = self.function(*args)
     92 if is_map(result):
     93     if len(result) != len(self.efferents) or not all(e in result for e in self.efferents):

File <string>:2, in wrapper_has_args_func(dwi, data_imap, mapping_imap, tractography_imap, segmentation_params, base_fname, tracking_params)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/decorators.py:133, in as_file.<locals>._as_file.<locals>.wrapper_as_file(*args, **kwargs)
    128 this_file = get_fname(
    129     base_fname, suffix,
    130     tracking_params=tracking_params,
    131     segmentation_params=segmentation_params)
    132 if not op.exists(this_file):
--> 133     img_trk_np_or_csv, meta = func(*args[:og_arg_count], **kwargs)
    135     logger.info(f"Saving {this_file}")
    136     if isinstance(img_trk_np_or_csv, nib.Nifti1Image):

File ~/anaconda3/lib/python3.10/site-packages/AFQ/tasks/segmentation.py:60, in segment(dwi, data_imap, mapping_imap, tractography_imap, segmentation_params)
     58 start_time = time()
     59 segmentation = seg.Segmentation(**segmentation_params)
---> 60 bundles = segmentation.segment(
     61     bundle_dict,
     62     tg,
     63     dwi,
     64     data_imap["bval"],
     65     data_imap["bvec"],
     66     reg_template=reg_template,
     67     mapping=mapping_imap["mapping"])
     69 seg_sft = aus.SegmentedSFT(bundles, Space.VOX)
     71 if len(seg_sft.sft) < 1:

File ~/anaconda3/lib/python3.10/site-packages/AFQ/segmentation.py:347, in Segmentation.segment(self, bundle_dict, tg, fdata, fbval, fbvec, mapping, reg_prealign, reg_template, img_affine, reset_tg_space)
    345     fiber_groups = self.segment_afq()
    346 elif self.seg_algo.startswith("reco"):
--> 347     fiber_groups = self.segment_reco()
    348 else:
    349     raise ValueError(f"The seg_algo input is {self.seg_algo}, which",
    350                      "is not recognized")

File ~/anaconda3/lib/python3.10/site-packages/AFQ/segmentation.py:954, in Segmentation.segment_reco(self, tg)
    952     rb = RecoBundles(self.moved_sl, verbose=False, rng=self.rng)
    953 # Next we'll iterate over bundles, registering each one:
--> 954 bundle_list = list(self.bundle_dict.keys())
    955 if 'whole_brain' in bundle_list:
    956     bundle_list.remove('whole_brain')

File ~/anaconda3/lib/python3.10/_collections_abc.py:886, in KeysView.__iter__(self)
    885 def __iter__(self):
--> 886     yield from self._mapping

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:373, in BundleDict.__iter__(self)
    372 def __iter__(self):
--> 373     self.gen_all()
    374     return iter(self._dict)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:308, in BundleDict.gen_all(self)
    306     if bundle_name not in self._dict:
    307         if not self.templates_loaded:
--> 308             self.load_templates()
    309         self._gen(bundle_name)
    310 if self.templates_loaded:

File ~/anaconda3/lib/python3.10/site-packages/AFQ/api/bundle_dict.py:219, in BundleDict.load_templates(self)
    217 elif self.seg_algo.startswith("reco"):
    218     if self.seg_algo.endswith("80"):
--> 219         self.templates = afd.read_hcp_atlas(80, as_file=True)
    220     else:
    221         self.templates = afd.read_hcp_atlas(16, as_file=True)

File ~/anaconda3/lib/python3.10/site-packages/AFQ/data/fetch.py:925, in read_hcp_atlas(n_bundles, as_file)
    923     atlas_folder = "Atlas_in_MNI_Space_16_bundles"
    924 elif n_bundles == 80:
--> 925     _, folder = fetch_hcp_atlas_80_bundles()
    926     atlas_folder = "Atlas_80_Bundles"
    928 whole_brain = op.join(
    929     folder,
    930     atlas_folder,
    931     'whole_brain',
    932     'whole_brain_MNI.trk')

File ~/anaconda3/lib/python3.10/site-packages/AFQ/data/fetch.py:78, in _make_reusable_fetcher.<locals>.fetcher()
     76     return files, folder
     77 else:
---> 78     return _make_fetcher(
     79         name, folder, baseurl, remote_fnames, local_fnames,
     80         doc=doc, **make_fetcher_kwargs)()

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:197, in _make_fetcher.<locals>.fetcher()
    194 for i, (f, n), in enumerate(zip(remote_fnames, local_fnames)):
    195     files[n] = (baseurl + f, md5_list[i] if
    196                 md5_list is not None else None)
--> 197 fetch_data(files, folder, data_size)
    199 if msg is not None:
    200     _log(msg)

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:146, in fetch_data(files, folder, data_size)
    144     all_skip = False
    145     _log('Downloading "%s" to %s' % (f, folder))
--> 146     _get_file_data(fullpath, url)
    147     check_md5(fullpath, md5)
    148 if all_skip:

File ~/anaconda3/lib/python3.10/site-packages/dipy/data/fetcher.py:96, in _get_file_data(fname, url)
     95 def _get_file_data(fname, url):
---> 96     with contextlib.closing(urlopen(url)) as opener:
     97         try:
     98             response_size = opener.headers['content-length']

File ~/anaconda3/lib/python3.10/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File ~/anaconda3/lib/python3.10/urllib/request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    523 for processor in self.process_response.get(protocol, []):
    524     meth = getattr(processor, meth_name)
--> 525     response = meth(req, response)
    527 return response

File ~/anaconda3/lib/python3.10/urllib/request.py:634, in HTTPErrorProcessor.http_response(self, request, response)
    631 # According to RFC 2616, "2xx" code indicates that the client's
    632 # request was successfully received, understood, and accepted.
    633 if not (200 <= code < 300):
--> 634     response = self.parent.error(
    635         'http', request, response, code, msg, hdrs)
    637 return response

File ~/anaconda3/lib/python3.10/urllib/request.py:563, in OpenerDirector.error(self, proto, *args)
    561 if http_err:
    562     args = (dict, 'default', 'http_error_default') + orig_args
--> 563     return self._call_chain(*args)

File ~/anaconda3/lib/python3.10/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File ~/anaconda3/lib/python3.10/urllib/request.py:643, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    642 def http_error_default(self, req, fp, code, msg, hdrs):
--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 403: Forbidden

**Comment by 36000** [comment]
Your python is having some issue with connecting to the internet. You can get around this by downloading the files you want directly, and putting them in the correct directory. In your case, it looks like you want this file: https://ndownloader.figshare.com/files/13638644

Then extract it and put it in AFQ_data, such that the README has this path:

**Comment by snaillyd** [comment]
Thanks a lot！The problem is solved.  I am using Anaconda3 on Ubuntu 20.04 and Windows 10. Is there something  about pyAFQ incompatible with Anaconda3?

**Comment by 36000** [comment]
This is not a problem with pyAFQ, it is a problem with python being able to connect to the internet. Maybe you are using a proxy server and need to configure python to know about it, or something like that?

Anyways, I am glad that this worked!
