### ISSUE TITLE
How to address `CsdNanResponseError`?

### ISSUE THREAD

**Issue by smeisler** [yeatmanlab/pyAFQ#974]
Hi,

I preprocessed data through QSIPrep (most recent version 0.18.0, but error also is present in 0.17.0) and ported outputs into the `pyafq_tractometry` recon spec. When I do, I get the `CsdNanResponseError` when fitting the CSD model. I do not know what steps to take to troubleshoot.

I have confirmed that the data can be used to create FODs from an MRTrix-based pipeline, and have checked that PyAFQ works on other data using my QSIPrep container. What should my next steps be?

For additional information, I am using raw data from the Natural Scenes Dataset (I am aware that full pre/postprocessed derivatives already exist for this dataset, but I for this application I would like to perform the processing). It has two pairs of AP/PA pairs with 98 and 99 directions. Preprocessing ran without errors.

My QSIPrep arguments included : 

`--output_resolution 1.25 --unringing-method mrdegibbs --pepolar-method TOPUP --denoise_method patch2self
`

Please let me know if any other information would help.

Thanks,
Steven

**Comment by smeisler** [comment]
After some more investigation, it looks like that none of the voxels hit the default FA threshold of 0.7.

**Comment by 36000** [comment]
Thank you for posting this issue, so that other people who have the same problem can use it as a reference!
