### ISSUE TITLE
Speed-memory tradeoff in reading from probability maps?

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#978]
In thinking about memory usage, @36000 noted that it is possible that the call out to `values_from_volume` in this part of the code:

https://github.com/yeatmanlab/pyAFQ/blob/71cd73a4b2f93e7a22570fff3c2d96e31fff6304/AFQ/segmentation.py#L579-L593

may require a large amount of memory. One way to trade off with speed would be to loop over streamlines, and check them each individually, instead of one concurrent indexing operation.

**Comment by arokem** [comment]
Importantly, if instead of an array, we were to pass a list, we would be using a loop inside `values_from_volume` (https://github.com/dipy/dipy/blob/master/dipy/tracking/streamline.py#L639C8-L645C49), so no need to implement a loop here.

**Comment by 36000** [comment]
We can continue this convo in #1033
