### ISSUE TITLE
Update to most recent pybids for faster indexing

### ISSUE THREAD

**Issue by pierre-nedelec** [yeatmanlab/pyAFQ#990]
`pybids` 0.16.2 has improved indexing speed (https://github.com/bids-standard/pybids/pull/1013). Would be nice to update to this:
https://github.com/yeatmanlab/pyAFQ/blob/0c4a726134d727f908cf4e23d1021d6b22ad3e90/setup.cfg#L33

**Comment by arokem** [comment]
Closed by #991
